package org.dynamislight.impl.vulkan;

import org.dynamislight.impl.vulkan.runtime.config.ReflectionProfile;
import org.dynamislight.impl.vulkan.runtime.config.VulkanRuntimeOptionParsing;

import java.util.Map;

final class VulkanReflectionTelemetryDefaults {
    private VulkanReflectionTelemetryDefaults() {
    }

    static final class State {
        double reflectionContactHardeningMinSsrMaxRoughness;
        double reflectionContactHardeningMinSsrStrength;
        int reflectionContactHardeningWarnCooldownFrames;
        int reflectionContactHardeningWarnMinFrames;
        int reflectionOverrideOtherWarnMax;
        double reflectionOverrideProbeOnlyRatioWarnMax;
        double reflectionOverrideSsrOnlyRatioWarnMax;
        int reflectionOverrideWarnCooldownFrames;
        int reflectionOverrideWarnMinFrames;
        double reflectionPlanarEnvelopeCoverageRatioWarnMin;
        double reflectionPlanarEnvelopePlaneDeltaWarnMax;
        int reflectionPlanarEnvelopeWarnCooldownFrames;
        int reflectionPlanarEnvelopeWarnMinFrames;
        double reflectionPlanarPerfDrawInflationWarnMax;
        double reflectionPlanarPerfMaxGpuMsHigh;
        double reflectionPlanarPerfMaxGpuMsLow;
        double reflectionPlanarPerfMaxGpuMsMedium;
        double reflectionPlanarPerfMaxGpuMsUltra;
        double reflectionPlanarPerfMemoryBudgetMb;
        int reflectionPlanarPerfWarnCooldownFrames;
        int reflectionPlanarPerfWarnMinFrames;
        int reflectionProbeChurnWarnCooldownFrames;
        int reflectionProbeChurnWarnMinDelta;
        int reflectionProbeChurnWarnMinStreak;
        int reflectionProbeQualityBleedRiskWarnMaxPairs;
        double reflectionProbeQualityBoxProjectionMinRatio;
        int reflectionProbeQualityInvalidBlendDistanceWarnMax;
        int reflectionProbeQualityMinOverlapPairsWhenMultiple;
        double reflectionProbeQualityOverlapCoverageWarnMin;
        int reflectionProbeQualityOverlapWarnMaxPairs;
        double reflectionProbeStreamingDeferredRatioWarnMax;
        double reflectionProbeStreamingLodSkewWarnMax;
        double reflectionProbeStreamingMemoryBudgetMb;
        double reflectionProbeStreamingMissRatioWarnMax;
        int reflectionProbeStreamingWarnCooldownFrames;
        int reflectionProbeStreamingWarnMinFrames;
        double reflectionRtAsBuildGpuMsWarnMax;
        double reflectionRtAsMemoryBudgetMb;
        double reflectionRtDenoiseSpatialVarianceWarnMax;
        double reflectionRtDenoiseStrength;
        double reflectionRtDenoiseTemporalLagWarnMax;
        int reflectionRtDenoiseWarnCooldownFrames;
        int reflectionRtDenoiseWarnMinFrames;
        double reflectionRtHybridProbeShareWarnMax;
        int reflectionRtHybridWarnCooldownFrames;
        int reflectionRtHybridWarnMinFrames;
        boolean reflectionRtMultiBounceEnabled;
        double reflectionRtPerfMaxGpuMsHigh;
        double reflectionRtPerfMaxGpuMsLow;
        double reflectionRtPerfMaxGpuMsMedium;
        double reflectionRtPerfMaxGpuMsUltra;
        int reflectionRtPerfWarnCooldownFrames;
        int reflectionRtPerfWarnMinFrames;
        boolean reflectionRtSingleBounceEnabled;
        boolean reflectionSsrTaaAdaptiveEnabled;
        double reflectionSsrTaaAdaptiveSsrStrengthScaleMin;
        double reflectionSsrTaaAdaptiveStepScaleBoostMax;
        double reflectionSsrTaaAdaptiveTemporalBoostMax;
        double reflectionSsrTaaAdaptiveTrendHighRatioWarnMin;
        double reflectionSsrTaaAdaptiveTrendSloHighRatioMax;
        double reflectionSsrTaaAdaptiveTrendSloMeanSeverityMax;
        int reflectionSsrTaaAdaptiveTrendSloMinSamples;
        int reflectionSsrTaaAdaptiveTrendWarnCooldownFrames;
        int reflectionSsrTaaAdaptiveTrendWarnMinFrames;
        int reflectionSsrTaaAdaptiveTrendWarnMinSamples;
        int reflectionSsrTaaAdaptiveTrendWindowFrames;
        double reflectionSsrTaaDisocclusionRejectConfidenceMax;
        long reflectionSsrTaaDisocclusionRejectDropEventsMin;
        double reflectionSsrTaaInstabilityConfidenceMax;
        long reflectionSsrTaaInstabilityDropEventsMin;
        double reflectionSsrTaaInstabilityRejectMin;
        int reflectionSsrTaaInstabilityWarnCooldownFrames;
        int reflectionSsrTaaInstabilityWarnMinFrames;
        double reflectionSsrTaaRiskEmaAlpha;
        double reflectionTransparencyCandidateReactiveMin;
        double reflectionTransparencyProbeOnlyRatioWarnMax;
        int reflectionTransparencyWarnCooldownFrames;
        int reflectionTransparencyWarnMinFrames;
    }

    static void apply(State state, ReflectionProfile profile, Map<String, String> backendOptions) {
        if (profile == ReflectionProfile.BALANCED) {
            return;
        }
        Map<String, String> safe = backendOptions == null ? Map.of() : backendOptions;
        switch (profile) {
            case PERFORMANCE -> {
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeChurnWarnMinDelta")) state.reflectionProbeChurnWarnMinDelta = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeChurnWarnMinStreak")) state.reflectionProbeChurnWarnMinStreak = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeChurnWarnCooldownFrames")) state.reflectionProbeChurnWarnCooldownFrames = 180;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityOverlapWarnMaxPairs")) state.reflectionProbeQualityOverlapWarnMaxPairs = 6;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityBleedRiskWarnMaxPairs")) state.reflectionProbeQualityBleedRiskWarnMaxPairs = 0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityMinOverlapPairsWhenMultiple")) state.reflectionProbeQualityMinOverlapPairsWhenMultiple = 1;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideProbeOnlyRatioWarnMax")) state.reflectionOverrideProbeOnlyRatioWarnMax = 0.55;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideSsrOnlyRatioWarnMax")) state.reflectionOverrideSsrOnlyRatioWarnMax = 0.55;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideOtherWarnMax")) state.reflectionOverrideOtherWarnMax = 0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideWarnMinFrames")) state.reflectionOverrideWarnMinFrames = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideWarnCooldownFrames")) state.reflectionOverrideWarnCooldownFrames = 180;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningMinSsrStrength")) state.reflectionContactHardeningMinSsrStrength = 0.30;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningMinSsrMaxRoughness")) state.reflectionContactHardeningMinSsrMaxRoughness = 0.50;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningWarnMinFrames")) state.reflectionContactHardeningWarnMinFrames = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningWarnCooldownFrames")) state.reflectionContactHardeningWarnCooldownFrames = 180;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityBoxProjectionMinRatio")) state.reflectionProbeQualityBoxProjectionMinRatio = 0.75;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityInvalidBlendDistanceWarnMax")) state.reflectionProbeQualityInvalidBlendDistanceWarnMax = 0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityOverlapCoverageWarnMin")) state.reflectionProbeQualityOverlapCoverageWarnMin = 0.20;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingWarnMinFrames")) state.reflectionProbeStreamingWarnMinFrames = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingWarnCooldownFrames")) state.reflectionProbeStreamingWarnCooldownFrames = 180;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingMissRatioWarnMax")) state.reflectionProbeStreamingMissRatioWarnMax = 0.20;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingDeferredRatioWarnMax")) state.reflectionProbeStreamingDeferredRatioWarnMax = 0.35;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingLodSkewWarnMax")) state.reflectionProbeStreamingLodSkewWarnMax = 0.55;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingMemoryBudgetMb")) state.reflectionProbeStreamingMemoryBudgetMb = 28.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityRejectMin")) state.reflectionSsrTaaInstabilityRejectMin = 0.45;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityConfidenceMax")) state.reflectionSsrTaaInstabilityConfidenceMax = 0.60;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityDropEventsMin")) state.reflectionSsrTaaInstabilityDropEventsMin = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityWarnMinFrames")) state.reflectionSsrTaaInstabilityWarnMinFrames = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityWarnCooldownFrames")) state.reflectionSsrTaaInstabilityWarnCooldownFrames = 240;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaRiskEmaAlpha")) state.reflectionSsrTaaRiskEmaAlpha = 0.20;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveEnabled")) state.reflectionSsrTaaAdaptiveEnabled = false;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTemporalBoostMax")) state.reflectionSsrTaaAdaptiveTemporalBoostMax = 0.08;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveSsrStrengthScaleMin")) state.reflectionSsrTaaAdaptiveSsrStrengthScaleMin = 0.80;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveStepScaleBoostMax")) state.reflectionSsrTaaAdaptiveStepScaleBoostMax = 0.10;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWindowFrames")) state.reflectionSsrTaaAdaptiveTrendWindowFrames = 150;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendHighRatioWarnMin")) state.reflectionSsrTaaAdaptiveTrendHighRatioWarnMin = 0.55;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWarnMinFrames")) state.reflectionSsrTaaAdaptiveTrendWarnMinFrames = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWarnCooldownFrames")) state.reflectionSsrTaaAdaptiveTrendWarnCooldownFrames = 240;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWarnMinSamples")) state.reflectionSsrTaaAdaptiveTrendWarnMinSamples = 30;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendSloMeanSeverityMax")) state.reflectionSsrTaaAdaptiveTrendSloMeanSeverityMax = 0.25;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendSloHighRatioMax")) state.reflectionSsrTaaAdaptiveTrendSloHighRatioMax = 0.20;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendSloMinSamples")) state.reflectionSsrTaaAdaptiveTrendSloMinSamples = 30;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaDisocclusionRejectDropEventsMin")) state.reflectionSsrTaaDisocclusionRejectDropEventsMin = 3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaDisocclusionRejectConfidenceMax")) state.reflectionSsrTaaDisocclusionRejectConfidenceMax = 0.58;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopePlaneDeltaWarnMax")) state.reflectionPlanarEnvelopePlaneDeltaWarnMax = 0.45;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopeCoverageRatioWarnMin")) state.reflectionPlanarEnvelopeCoverageRatioWarnMin = 0.30;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopeWarnMinFrames")) state.reflectionPlanarEnvelopeWarnMinFrames = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopeWarnCooldownFrames")) state.reflectionPlanarEnvelopeWarnCooldownFrames = 180;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsLow")) state.reflectionPlanarPerfMaxGpuMsLow = 1.2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsMedium")) state.reflectionPlanarPerfMaxGpuMsMedium = 1.9;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsHigh")) state.reflectionPlanarPerfMaxGpuMsHigh = 2.6;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsUltra")) state.reflectionPlanarPerfMaxGpuMsUltra = 3.2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfDrawInflationWarnMax")) state.reflectionPlanarPerfDrawInflationWarnMax = 1.7;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMemoryBudgetMb")) state.reflectionPlanarPerfMemoryBudgetMb = 20.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfWarnMinFrames")) state.reflectionPlanarPerfWarnMinFrames = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfWarnCooldownFrames")) state.reflectionPlanarPerfWarnCooldownFrames = 180;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtSingleBounceEnabled")) state.reflectionRtSingleBounceEnabled = true;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtMultiBounceEnabled")) state.reflectionRtMultiBounceEnabled = false;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseStrength")) state.reflectionRtDenoiseStrength = 0.58;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsLow")) state.reflectionRtPerfMaxGpuMsLow = 1.4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsMedium")) state.reflectionRtPerfMaxGpuMsMedium = 2.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsHigh")) state.reflectionRtPerfMaxGpuMsHigh = 2.8;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsUltra")) state.reflectionRtPerfMaxGpuMsUltra = 3.6;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfWarnMinFrames")) state.reflectionRtPerfWarnMinFrames = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfWarnCooldownFrames")) state.reflectionRtPerfWarnCooldownFrames = 180;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtHybridProbeShareWarnMax")) state.reflectionRtHybridProbeShareWarnMax = 0.58;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtHybridWarnMinFrames")) state.reflectionRtHybridWarnMinFrames = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtHybridWarnCooldownFrames")) state.reflectionRtHybridWarnCooldownFrames = 180;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseSpatialVarianceWarnMax")) state.reflectionRtDenoiseSpatialVarianceWarnMax = 0.34;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseTemporalLagWarnMax")) state.reflectionRtDenoiseTemporalLagWarnMax = 0.30;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseWarnMinFrames")) state.reflectionRtDenoiseWarnMinFrames = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseWarnCooldownFrames")) state.reflectionRtDenoiseWarnCooldownFrames = 180;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtAsBuildGpuMsWarnMax")) state.reflectionRtAsBuildGpuMsWarnMax = 1.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtAsMemoryBudgetMb")) state.reflectionRtAsMemoryBudgetMb = 48.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyCandidateReactiveMin")) state.reflectionTransparencyCandidateReactiveMin = 0.45;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyProbeOnlyRatioWarnMax")) state.reflectionTransparencyProbeOnlyRatioWarnMax = 0.50;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyWarnMinFrames")) state.reflectionTransparencyWarnMinFrames = 4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyWarnCooldownFrames")) state.reflectionTransparencyWarnCooldownFrames = 180;
            }
            case QUALITY -> {
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeChurnWarnMinDelta")) state.reflectionProbeChurnWarnMinDelta = 1;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeChurnWarnMinStreak")) state.reflectionProbeChurnWarnMinStreak = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeChurnWarnCooldownFrames")) state.reflectionProbeChurnWarnCooldownFrames = 90;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityOverlapWarnMaxPairs")) state.reflectionProbeQualityOverlapWarnMaxPairs = 10;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityBleedRiskWarnMaxPairs")) state.reflectionProbeQualityBleedRiskWarnMaxPairs = 1;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityMinOverlapPairsWhenMultiple")) state.reflectionProbeQualityMinOverlapPairsWhenMultiple = 1;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideProbeOnlyRatioWarnMax")) state.reflectionOverrideProbeOnlyRatioWarnMax = 0.75;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideSsrOnlyRatioWarnMax")) state.reflectionOverrideSsrOnlyRatioWarnMax = 0.75;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideOtherWarnMax")) state.reflectionOverrideOtherWarnMax = 0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideWarnMinFrames")) state.reflectionOverrideWarnMinFrames = 3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideWarnCooldownFrames")) state.reflectionOverrideWarnCooldownFrames = 120;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningMinSsrStrength")) state.reflectionContactHardeningMinSsrStrength = 0.35;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningMinSsrMaxRoughness")) state.reflectionContactHardeningMinSsrMaxRoughness = 0.55;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningWarnMinFrames")) state.reflectionContactHardeningWarnMinFrames = 3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningWarnCooldownFrames")) state.reflectionContactHardeningWarnCooldownFrames = 120;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityBoxProjectionMinRatio")) state.reflectionProbeQualityBoxProjectionMinRatio = 0.60;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityInvalidBlendDistanceWarnMax")) state.reflectionProbeQualityInvalidBlendDistanceWarnMax = 0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityOverlapCoverageWarnMin")) state.reflectionProbeQualityOverlapCoverageWarnMin = 0.12;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingWarnMinFrames")) state.reflectionProbeStreamingWarnMinFrames = 3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingWarnCooldownFrames")) state.reflectionProbeStreamingWarnCooldownFrames = 120;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingMissRatioWarnMax")) state.reflectionProbeStreamingMissRatioWarnMax = 0.35;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingDeferredRatioWarnMax")) state.reflectionProbeStreamingDeferredRatioWarnMax = 0.55;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingLodSkewWarnMax")) state.reflectionProbeStreamingLodSkewWarnMax = 0.70;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingMemoryBudgetMb")) state.reflectionProbeStreamingMemoryBudgetMb = 52.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityRejectMin")) state.reflectionSsrTaaInstabilityRejectMin = 0.32;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityConfidenceMax")) state.reflectionSsrTaaInstabilityConfidenceMax = 0.74;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityDropEventsMin")) state.reflectionSsrTaaInstabilityDropEventsMin = 0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityWarnMinFrames")) state.reflectionSsrTaaInstabilityWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityWarnCooldownFrames")) state.reflectionSsrTaaInstabilityWarnCooldownFrames = 90;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaRiskEmaAlpha")) state.reflectionSsrTaaRiskEmaAlpha = 0.30;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveEnabled")) state.reflectionSsrTaaAdaptiveEnabled = false;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTemporalBoostMax")) state.reflectionSsrTaaAdaptiveTemporalBoostMax = 0.12;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveSsrStrengthScaleMin")) state.reflectionSsrTaaAdaptiveSsrStrengthScaleMin = 0.70;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveStepScaleBoostMax")) state.reflectionSsrTaaAdaptiveStepScaleBoostMax = 0.15;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWindowFrames")) state.reflectionSsrTaaAdaptiveTrendWindowFrames = 120;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendHighRatioWarnMin")) state.reflectionSsrTaaAdaptiveTrendHighRatioWarnMin = 0.45;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWarnMinFrames")) state.reflectionSsrTaaAdaptiveTrendWarnMinFrames = 3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWarnCooldownFrames")) state.reflectionSsrTaaAdaptiveTrendWarnCooldownFrames = 120;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWarnMinSamples")) state.reflectionSsrTaaAdaptiveTrendWarnMinSamples = 24;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendSloMeanSeverityMax")) state.reflectionSsrTaaAdaptiveTrendSloMeanSeverityMax = 0.40;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendSloHighRatioMax")) state.reflectionSsrTaaAdaptiveTrendSloHighRatioMax = 0.30;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendSloMinSamples")) state.reflectionSsrTaaAdaptiveTrendSloMinSamples = 24;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaDisocclusionRejectDropEventsMin")) state.reflectionSsrTaaDisocclusionRejectDropEventsMin = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaDisocclusionRejectConfidenceMax")) state.reflectionSsrTaaDisocclusionRejectConfidenceMax = 0.62;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopePlaneDeltaWarnMax")) state.reflectionPlanarEnvelopePlaneDeltaWarnMax = 0.30;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopeCoverageRatioWarnMin")) state.reflectionPlanarEnvelopeCoverageRatioWarnMin = 0.20;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopeWarnMinFrames")) state.reflectionPlanarEnvelopeWarnMinFrames = 3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopeWarnCooldownFrames")) state.reflectionPlanarEnvelopeWarnCooldownFrames = 120;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsLow")) state.reflectionPlanarPerfMaxGpuMsLow = 1.5;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsMedium")) state.reflectionPlanarPerfMaxGpuMsMedium = 2.4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsHigh")) state.reflectionPlanarPerfMaxGpuMsHigh = 3.3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsUltra")) state.reflectionPlanarPerfMaxGpuMsUltra = 4.5;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfDrawInflationWarnMax")) state.reflectionPlanarPerfDrawInflationWarnMax = 2.1;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMemoryBudgetMb")) state.reflectionPlanarPerfMemoryBudgetMb = 36.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfWarnMinFrames")) state.reflectionPlanarPerfWarnMinFrames = 3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfWarnCooldownFrames")) state.reflectionPlanarPerfWarnCooldownFrames = 120;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtSingleBounceEnabled")) state.reflectionRtSingleBounceEnabled = true;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtMultiBounceEnabled")) state.reflectionRtMultiBounceEnabled = true;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseStrength")) state.reflectionRtDenoiseStrength = 0.72;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsLow")) state.reflectionRtPerfMaxGpuMsLow = 1.8;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsMedium")) state.reflectionRtPerfMaxGpuMsMedium = 2.8;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsHigh")) state.reflectionRtPerfMaxGpuMsHigh = 3.9;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsUltra")) state.reflectionRtPerfMaxGpuMsUltra = 5.2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfWarnMinFrames")) state.reflectionRtPerfWarnMinFrames = 3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfWarnCooldownFrames")) state.reflectionRtPerfWarnCooldownFrames = 120;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtHybridProbeShareWarnMax")) state.reflectionRtHybridProbeShareWarnMax = 0.72;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtHybridWarnMinFrames")) state.reflectionRtHybridWarnMinFrames = 3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtHybridWarnCooldownFrames")) state.reflectionRtHybridWarnCooldownFrames = 120;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseSpatialVarianceWarnMax")) state.reflectionRtDenoiseSpatialVarianceWarnMax = 0.48;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseTemporalLagWarnMax")) state.reflectionRtDenoiseTemporalLagWarnMax = 0.38;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseWarnMinFrames")) state.reflectionRtDenoiseWarnMinFrames = 3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseWarnCooldownFrames")) state.reflectionRtDenoiseWarnCooldownFrames = 120;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtAsBuildGpuMsWarnMax")) state.reflectionRtAsBuildGpuMsWarnMax = 1.4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtAsMemoryBudgetMb")) state.reflectionRtAsMemoryBudgetMb = 80.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyCandidateReactiveMin")) state.reflectionTransparencyCandidateReactiveMin = 0.35;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyProbeOnlyRatioWarnMax")) state.reflectionTransparencyProbeOnlyRatioWarnMax = 0.65;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyWarnMinFrames")) state.reflectionTransparencyWarnMinFrames = 3;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyWarnCooldownFrames")) state.reflectionTransparencyWarnCooldownFrames = 120;
            }
            case STABILITY -> {
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeChurnWarnMinDelta")) state.reflectionProbeChurnWarnMinDelta = 1;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeChurnWarnMinStreak")) state.reflectionProbeChurnWarnMinStreak = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeChurnWarnCooldownFrames")) state.reflectionProbeChurnWarnCooldownFrames = 60;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityOverlapWarnMaxPairs")) state.reflectionProbeQualityOverlapWarnMaxPairs = 12;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityBleedRiskWarnMaxPairs")) state.reflectionProbeQualityBleedRiskWarnMaxPairs = 1;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityMinOverlapPairsWhenMultiple")) state.reflectionProbeQualityMinOverlapPairsWhenMultiple = 1;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideProbeOnlyRatioWarnMax")) state.reflectionOverrideProbeOnlyRatioWarnMax = 0.85;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideSsrOnlyRatioWarnMax")) state.reflectionOverrideSsrOnlyRatioWarnMax = 0.85;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideOtherWarnMax")) state.reflectionOverrideOtherWarnMax = 1;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideWarnMinFrames")) state.reflectionOverrideWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.overrideWarnCooldownFrames")) state.reflectionOverrideWarnCooldownFrames = 90;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningMinSsrStrength")) state.reflectionContactHardeningMinSsrStrength = 0.25;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningMinSsrMaxRoughness")) state.reflectionContactHardeningMinSsrMaxRoughness = 0.45;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningWarnMinFrames")) state.reflectionContactHardeningWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.contactHardeningWarnCooldownFrames")) state.reflectionContactHardeningWarnCooldownFrames = 90;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityBoxProjectionMinRatio")) state.reflectionProbeQualityBoxProjectionMinRatio = 0.45;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityInvalidBlendDistanceWarnMax")) state.reflectionProbeQualityInvalidBlendDistanceWarnMax = 1;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeQualityOverlapCoverageWarnMin")) state.reflectionProbeQualityOverlapCoverageWarnMin = 0.08;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingWarnMinFrames")) state.reflectionProbeStreamingWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingWarnCooldownFrames")) state.reflectionProbeStreamingWarnCooldownFrames = 90;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingMissRatioWarnMax")) state.reflectionProbeStreamingMissRatioWarnMax = 0.45;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingDeferredRatioWarnMax")) state.reflectionProbeStreamingDeferredRatioWarnMax = 0.70;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingLodSkewWarnMax")) state.reflectionProbeStreamingLodSkewWarnMax = 0.80;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.probeStreamingMemoryBudgetMb")) state.reflectionProbeStreamingMemoryBudgetMb = 72.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityRejectMin")) state.reflectionSsrTaaInstabilityRejectMin = 0.28;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityConfidenceMax")) state.reflectionSsrTaaInstabilityConfidenceMax = 0.78;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityDropEventsMin")) state.reflectionSsrTaaInstabilityDropEventsMin = 0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityWarnMinFrames")) state.reflectionSsrTaaInstabilityWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaInstabilityWarnCooldownFrames")) state.reflectionSsrTaaInstabilityWarnCooldownFrames = 60;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaRiskEmaAlpha")) state.reflectionSsrTaaRiskEmaAlpha = 0.45;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveEnabled")) state.reflectionSsrTaaAdaptiveEnabled = true;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTemporalBoostMax")) state.reflectionSsrTaaAdaptiveTemporalBoostMax = 0.18;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveSsrStrengthScaleMin")) state.reflectionSsrTaaAdaptiveSsrStrengthScaleMin = 0.60;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveStepScaleBoostMax")) state.reflectionSsrTaaAdaptiveStepScaleBoostMax = 0.25;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWindowFrames")) state.reflectionSsrTaaAdaptiveTrendWindowFrames = 180;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendHighRatioWarnMin")) state.reflectionSsrTaaAdaptiveTrendHighRatioWarnMin = 0.30;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWarnMinFrames")) state.reflectionSsrTaaAdaptiveTrendWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWarnCooldownFrames")) state.reflectionSsrTaaAdaptiveTrendWarnCooldownFrames = 90;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendWarnMinSamples")) state.reflectionSsrTaaAdaptiveTrendWarnMinSamples = 16;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendSloMeanSeverityMax")) state.reflectionSsrTaaAdaptiveTrendSloMeanSeverityMax = 0.65;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendSloHighRatioMax")) state.reflectionSsrTaaAdaptiveTrendSloHighRatioMax = 0.45;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaAdaptiveTrendSloMinSamples")) state.reflectionSsrTaaAdaptiveTrendSloMinSamples = 16;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaDisocclusionRejectDropEventsMin")) state.reflectionSsrTaaDisocclusionRejectDropEventsMin = 1;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.ssrTaaDisocclusionRejectConfidenceMax")) state.reflectionSsrTaaDisocclusionRejectConfidenceMax = 0.70;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopePlaneDeltaWarnMax")) state.reflectionPlanarEnvelopePlaneDeltaWarnMax = 0.22;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopeCoverageRatioWarnMin")) state.reflectionPlanarEnvelopeCoverageRatioWarnMin = 0.15;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopeWarnMinFrames")) state.reflectionPlanarEnvelopeWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarEnvelopeWarnCooldownFrames")) state.reflectionPlanarEnvelopeWarnCooldownFrames = 90;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsLow")) state.reflectionPlanarPerfMaxGpuMsLow = 1.8;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsMedium")) state.reflectionPlanarPerfMaxGpuMsMedium = 2.8;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsHigh")) state.reflectionPlanarPerfMaxGpuMsHigh = 3.8;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMaxGpuMsUltra")) state.reflectionPlanarPerfMaxGpuMsUltra = 5.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfDrawInflationWarnMax")) state.reflectionPlanarPerfDrawInflationWarnMax = 2.4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfMemoryBudgetMb")) state.reflectionPlanarPerfMemoryBudgetMb = 48.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfWarnMinFrames")) state.reflectionPlanarPerfWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.planarPerfWarnCooldownFrames")) state.reflectionPlanarPerfWarnCooldownFrames = 90;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtSingleBounceEnabled")) state.reflectionRtSingleBounceEnabled = true;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtMultiBounceEnabled")) state.reflectionRtMultiBounceEnabled = false;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseStrength")) state.reflectionRtDenoiseStrength = 0.80;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsLow")) state.reflectionRtPerfMaxGpuMsLow = 2.2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsMedium")) state.reflectionRtPerfMaxGpuMsMedium = 3.2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsHigh")) state.reflectionRtPerfMaxGpuMsHigh = 4.4;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfMaxGpuMsUltra")) state.reflectionRtPerfMaxGpuMsUltra = 5.8;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfWarnMinFrames")) state.reflectionRtPerfWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtPerfWarnCooldownFrames")) state.reflectionRtPerfWarnCooldownFrames = 90;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtHybridProbeShareWarnMax")) state.reflectionRtHybridProbeShareWarnMax = 0.76;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtHybridWarnMinFrames")) state.reflectionRtHybridWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtHybridWarnCooldownFrames")) state.reflectionRtHybridWarnCooldownFrames = 90;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseSpatialVarianceWarnMax")) state.reflectionRtDenoiseSpatialVarianceWarnMax = 0.54;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseTemporalLagWarnMax")) state.reflectionRtDenoiseTemporalLagWarnMax = 0.42;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseWarnMinFrames")) state.reflectionRtDenoiseWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtDenoiseWarnCooldownFrames")) state.reflectionRtDenoiseWarnCooldownFrames = 90;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtAsBuildGpuMsWarnMax")) state.reflectionRtAsBuildGpuMsWarnMax = 1.8;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.rtAsMemoryBudgetMb")) state.reflectionRtAsMemoryBudgetMb = 96.0;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyCandidateReactiveMin")) state.reflectionTransparencyCandidateReactiveMin = 0.25;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyProbeOnlyRatioWarnMax")) state.reflectionTransparencyProbeOnlyRatioWarnMax = 0.75;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyWarnMinFrames")) state.reflectionTransparencyWarnMinFrames = 2;
                if (!VulkanRuntimeOptionParsing.hasBackendOption(safe, "vulkan.reflections.transparencyWarnCooldownFrames")) state.reflectionTransparencyWarnCooldownFrames = 90;
            }
            default -> {
            }
        }
    }

}
