package org.dynamislight.impl.vulkan;

import org.dynamislight.impl.vulkan.state.VulkanTelemetryStateBinder;

import java.util.List;

final class VulkanRuntimeWarningResets {
    static final class ReflectionDisabledState {
        String reflectionPlanarPassOrderContractStatus;
        int reflectionPlanarScopedMeshEligibleCount;
        int reflectionPlanarScopedMeshExcludedCount;
        boolean reflectionPlanarMirrorCameraActive;
        boolean reflectionPlanarDedicatedCaptureLaneActive;
        boolean reflectionRtLaneRequested;
        boolean reflectionRtLaneActive;
        boolean reflectionRtRequireActiveUnmetLastFrame;
        boolean reflectionRtRequireMultiBounceUnmetLastFrame;
        boolean reflectionRtRequireDedicatedPipelineUnmetLastFrame;
        String reflectionRtFallbackChainActive;
        boolean reflectionRtTraversalSupported;
        boolean reflectionRtDedicatedCapabilitySupported;
        boolean reflectionRtDedicatedHardwarePipelineActive;
        String reflectionRtBlasLifecycleState;
        String reflectionRtTlasLifecycleState;
        String reflectionRtSbtLifecycleState;
        int reflectionRtBlasObjectCount;
        int reflectionRtTlasInstanceCount;
        int reflectionRtSbtRecordCount;
        double reflectionRtHybridRtShare;
        double reflectionRtHybridSsrShare;
        double reflectionRtHybridProbeShare;
        boolean reflectionRtHybridBreachedLastFrame;
        int reflectionRtPerfHighStreak;
        int reflectionRtPerfWarnCooldownRemaining;
        double reflectionRtPerfLastGpuMsEstimate;
        double reflectionRtPerfLastGpuMsCap;
        boolean reflectionRtPerfBreachedLastFrame;
        boolean reflectionRtPromotionReadyLastFrame;
        int reflectionRtPromotionReadyHighStreak;
        int reflectionProbeStreamingHighStreak;
        int reflectionProbeStreamingWarnCooldownRemaining;
        boolean reflectionProbeStreamingBreachedLastFrame;
        int reflectionTransparentCandidateCount;
        String reflectionTransparencyStageGateStatus;
        String reflectionTransparencyFallbackPath;
    }

    static final class ShadowFrameDefaultsState {
        String shadowCapabilityFeatureIdLastFrame;
        String shadowCapabilityModeLastFrame;
        List<String> shadowCapabilitySignalsLastFrame;
        int shadowCadenceSelectedLocalLightsLastFrame;
        int shadowCadenceDeferredLocalLightsLastFrame;
        int shadowCadenceStaleBypassCountLastFrame;
        double shadowCadenceDeferredRatioLastFrame;
        boolean shadowCadencePromotionReadyLastFrame;
        boolean shadowCadenceEnvelopeBreachedLastFrame;
        int shadowPointBudgetRenderedCubemapsLastFrame;
        int shadowPointBudgetRenderedFacesLastFrame;
        int shadowPointBudgetDeferredCountLastFrame;
        double shadowPointBudgetSaturationRatioLastFrame;
        boolean shadowPointBudgetPromotionReadyLastFrame;
        boolean shadowPointBudgetEnvelopeBreachedLastFrame;
        int shadowCacheHitCountLastFrame;
        int shadowCacheMissCountLastFrame;
        int shadowCacheEvictionCountLastFrame;
        double shadowCacheHitRatioLastFrame;
        double shadowCacheChurnRatioLastFrame;
        String shadowCacheInvalidationReasonLastFrame;
        boolean shadowCacheEnvelopeBreachedLastFrame;
        double shadowRtPerfGpuMsEstimateLastFrame;
        double shadowRtPerfGpuMsWarnMaxLastFrame;
        boolean shadowRtEnvelopeBreachedLastFrame;
        double shadowHybridCascadeShareLastFrame;
        double shadowHybridContactShareLastFrame;
        double shadowHybridRtShareLastFrame;
        boolean shadowHybridEnvelopeBreachedLastFrame;
        int shadowTransparentReceiverCandidateCountLastFrame;
        double shadowTransparentReceiverCandidateRatioLastFrame;
        String shadowTransparentReceiverPolicyLastFrame;
        boolean shadowTransparentReceiverEnvelopeBreachedLastFrame;
        boolean shadowAreaApproxBreachedLastFrame;
        boolean shadowDistanceFieldBreachedLastFrame;
        int shadowTopologyCandidateSpotLightsLastFrame;
        int shadowTopologyCandidatePointLightsLastFrame;
        double shadowTopologyLocalCoverageLastFrame;
        double shadowTopologySpotCoverageLastFrame;
        double shadowTopologyPointCoverageLastFrame;
        boolean shadowTopologyPromotionReadyLastFrame;
        boolean shadowTopologyEnvelopeBreachedLastFrame;
        boolean shadowSpotProjectedRequestedLastFrame;
        boolean shadowSpotProjectedActiveLastFrame;
        int shadowSpotProjectedRenderedCountLastFrame;
        String shadowSpotProjectedContractStatusLastFrame;
        boolean shadowSpotProjectedContractBreachedLastFrame;
        boolean shadowSpotProjectedPromotionReadyLastFrame;
        boolean shadowPhaseAPromotionReadyLastFrame;
        boolean shadowPhaseDPromotionReadyLastFrame;
    }

    static void resetReflectionWhenDisabled(Object runtime, double rtPerfCapForTier) {
        ReflectionDisabledState state = new ReflectionDisabledState();
        VulkanTelemetryStateBinder.copyMatchingFields(runtime, state);
        state.reflectionPlanarPassOrderContractStatus = "inactive";
        state.reflectionPlanarScopedMeshEligibleCount = 0;
        state.reflectionPlanarScopedMeshExcludedCount = 0;
        state.reflectionPlanarMirrorCameraActive = false;
        state.reflectionPlanarDedicatedCaptureLaneActive = false;
        state.reflectionRtLaneRequested = false;
        state.reflectionRtLaneActive = false;
        state.reflectionRtRequireActiveUnmetLastFrame = false;
        state.reflectionRtRequireMultiBounceUnmetLastFrame = false;
        state.reflectionRtRequireDedicatedPipelineUnmetLastFrame = false;
        state.reflectionRtFallbackChainActive = "probe";
        state.reflectionRtTraversalSupported = false;
        state.reflectionRtDedicatedCapabilitySupported = false;
        state.reflectionRtDedicatedHardwarePipelineActive = false;
        state.reflectionRtBlasLifecycleState = "disabled";
        state.reflectionRtTlasLifecycleState = "disabled";
        state.reflectionRtSbtLifecycleState = "disabled";
        state.reflectionRtBlasObjectCount = 0;
        state.reflectionRtTlasInstanceCount = 0;
        state.reflectionRtSbtRecordCount = 0;
        state.reflectionRtHybridRtShare = 0.0;
        state.reflectionRtHybridSsrShare = 0.0;
        state.reflectionRtHybridProbeShare = 1.0;
        state.reflectionRtHybridBreachedLastFrame = false;
        state.reflectionRtPerfHighStreak = 0;
        state.reflectionRtPerfWarnCooldownRemaining = 0;
        state.reflectionRtPerfLastGpuMsEstimate = 0.0;
        state.reflectionRtPerfLastGpuMsCap = rtPerfCapForTier;
        state.reflectionRtPerfBreachedLastFrame = false;
        state.reflectionRtPromotionReadyLastFrame = false;
        state.reflectionRtPromotionReadyHighStreak = 0;
        state.reflectionProbeStreamingHighStreak = 0;
        state.reflectionProbeStreamingWarnCooldownRemaining = 0;
        state.reflectionProbeStreamingBreachedLastFrame = false;
        state.reflectionTransparentCandidateCount = 0;
        state.reflectionTransparencyStageGateStatus = "not_required";
        state.reflectionTransparencyFallbackPath = "none";
        VulkanTelemetryStateBinder.copyMatchingFields(state, runtime);
    }

    static void resetShadowFrameDefaults(Object runtime, boolean transparentReceiversSupported) {
        ShadowFrameDefaultsState state = new ShadowFrameDefaultsState();
        VulkanTelemetryStateBinder.copyMatchingFields(runtime, state);
        state.shadowCapabilityFeatureIdLastFrame = "unavailable";
        state.shadowCapabilityModeLastFrame = "unavailable";
        state.shadowCapabilitySignalsLastFrame = List.of();
        state.shadowCadenceSelectedLocalLightsLastFrame = 0;
        state.shadowCadenceDeferredLocalLightsLastFrame = 0;
        state.shadowCadenceStaleBypassCountLastFrame = 0;
        state.shadowCadenceDeferredRatioLastFrame = 0.0;
        state.shadowCadencePromotionReadyLastFrame = false;
        state.shadowCadenceEnvelopeBreachedLastFrame = false;
        state.shadowPointBudgetRenderedCubemapsLastFrame = 0;
        state.shadowPointBudgetRenderedFacesLastFrame = 0;
        state.shadowPointBudgetDeferredCountLastFrame = 0;
        state.shadowPointBudgetSaturationRatioLastFrame = 0.0;
        state.shadowPointBudgetPromotionReadyLastFrame = false;
        state.shadowPointBudgetEnvelopeBreachedLastFrame = false;
        state.shadowCacheHitCountLastFrame = 0;
        state.shadowCacheMissCountLastFrame = 0;
        state.shadowCacheEvictionCountLastFrame = 0;
        state.shadowCacheHitRatioLastFrame = 0.0;
        state.shadowCacheChurnRatioLastFrame = 0.0;
        state.shadowCacheInvalidationReasonLastFrame = "inactive";
        state.shadowCacheEnvelopeBreachedLastFrame = false;
        state.shadowRtPerfGpuMsEstimateLastFrame = 0.0;
        state.shadowRtPerfGpuMsWarnMaxLastFrame = 0.0;
        state.shadowRtEnvelopeBreachedLastFrame = false;
        state.shadowHybridCascadeShareLastFrame = 1.0;
        state.shadowHybridContactShareLastFrame = 0.0;
        state.shadowHybridRtShareLastFrame = 0.0;
        state.shadowHybridEnvelopeBreachedLastFrame = false;
        state.shadowTransparentReceiverCandidateCountLastFrame = 0;
        state.shadowTransparentReceiverCandidateRatioLastFrame = 0.0;
        state.shadowTransparentReceiverPolicyLastFrame = transparentReceiversSupported ? "enabled" : "fallback_opaque_only";
        state.shadowTransparentReceiverEnvelopeBreachedLastFrame = false;
        state.shadowAreaApproxBreachedLastFrame = false;
        state.shadowDistanceFieldBreachedLastFrame = false;
        state.shadowTopologyCandidateSpotLightsLastFrame = 0;
        state.shadowTopologyCandidatePointLightsLastFrame = 0;
        state.shadowTopologyLocalCoverageLastFrame = 0.0;
        state.shadowTopologySpotCoverageLastFrame = 0.0;
        state.shadowTopologyPointCoverageLastFrame = 0.0;
        state.shadowTopologyPromotionReadyLastFrame = false;
        state.shadowTopologyEnvelopeBreachedLastFrame = false;
        state.shadowSpotProjectedRequestedLastFrame = false;
        state.shadowSpotProjectedActiveLastFrame = false;
        state.shadowSpotProjectedRenderedCountLastFrame = 0;
        state.shadowSpotProjectedContractStatusLastFrame = "unavailable";
        state.shadowSpotProjectedContractBreachedLastFrame = false;
        state.shadowSpotProjectedPromotionReadyLastFrame = false;
        state.shadowPhaseAPromotionReadyLastFrame = false;
        state.shadowPhaseDPromotionReadyLastFrame = false;
        VulkanTelemetryStateBinder.copyMatchingFields(state, runtime);
    }

    private VulkanRuntimeWarningResets() {
    }
}
