package org.dynamislight.impl.vulkan.command;

import java.util.List;
import java.util.function.IntUnaryOperator;
import org.dynamislight.impl.vulkan.model.VulkanGpuMesh;
import org.dynamislight.impl.vulkan.model.VulkanInstanceBatch;

public final class VulkanFrameCommandInputsFactory {
    private VulkanFrameCommandInputsFactory() {
    }

    public static VulkanFrameCommandOrchestrator.Inputs create(Inputs inputs) {
        return new VulkanFrameCommandOrchestrator.Inputs(
                inputs.gpuMeshes(),
                inputs.instanceBatches(),
                inputs.indirectDrawBuffer(),
                inputs.drawMetaBuffer(),
                inputs.cullingComputePass(),
                inputs.viewProjMatrix(),
                inputs.bindlessActive(),
                inputs.bindlessDescriptorSet(),
                inputs.bindlessDescriptorHeap(),
                inputs.maxDynamicSceneObjects(),
                inputs.swapchainWidth(),
                inputs.swapchainHeight(),
                inputs.swapchainImageFormat(),
                inputs.depthFormat(),
                inputs.shadowMapResolution(),
                inputs.shadowEnabled(),
                inputs.pointShadowEnabled(),
                inputs.shadowCascadeCount(),
                inputs.maxShadowMatrices(),
                inputs.maxShadowCascades(),
                inputs.pointShadowFaces(),
                inputs.renderPass(),
                inputs.framebuffers(),
                inputs.mainGeometryPipeline(),
                inputs.mainGeometryPipelineLayout(),
                inputs.mainGeometryBindlessStaticPipeline(),
                inputs.mainGeometryBindlessStaticPipelineLayout(),
                inputs.mainGeometryBindlessSkinnedPipeline(),
                inputs.mainGeometryBindlessSkinnedPipelineLayout(),
                inputs.mainGeometryBindlessMorphPipeline(),
                inputs.mainGeometryBindlessMorphPipelineLayout(),
                inputs.mainGeometryBindlessSkinnedMorphPipeline(),
                inputs.mainGeometryBindlessSkinnedMorphPipelineLayout(),
                inputs.mainGeometryBindlessInstancedPipeline(),
                inputs.mainGeometryBindlessInstancedPipelineLayout(),
                inputs.mainGeometryMorphPipeline(),
                inputs.mainGeometryMorphPipelineLayout(),
                inputs.mainGeometrySkinnedPipeline(),
                inputs.mainGeometrySkinnedPipelineLayout(),
                inputs.mainGeometrySkinnedMorphPipeline(),
                inputs.mainGeometrySkinnedMorphPipelineLayout(),
                inputs.mainGeometryInstancedPipeline(),
                inputs.mainGeometryInstancedPipelineLayout(),
                inputs.shadowRenderPass(),
                inputs.shadowPipeline(),
                inputs.shadowInstancedPipeline(),
                inputs.shadowBindlessInstancedPipeline(),
                inputs.shadowPipelineLayout(),
                inputs.shadowFramebuffers(),
                inputs.shadowDepthImage(),
                inputs.shadowMomentImage(),
                inputs.shadowMomentFormat(),
                inputs.shadowMomentMipLevels(),
                inputs.shadowMomentPipelineRequested(),
                inputs.shadowMomentInitialized(),
                inputs.postOffscreenActive(),
                inputs.postIntermediateInitialized(),
                inputs.tonemapEnabled(),
                inputs.tonemapExposure(),
                inputs.tonemapGamma(),
                inputs.ssaoEnabled(),
                inputs.bloomEnabled(),
                inputs.bloomThreshold(),
                inputs.bloomStrength(),
                inputs.ssaoStrength(),
                inputs.ssaoRadius(),
                inputs.ssaoBias(),
                inputs.ssaoPower(),
                inputs.smaaEnabled(),
                inputs.smaaStrength(),
                inputs.taaEnabled(),
                inputs.taaBlend(),
                inputs.taaHistoryInitialized(),
                inputs.taaJitterUvDeltaX(),
                inputs.taaJitterUvDeltaY(),
                inputs.taaMotionUvX(),
                inputs.taaMotionUvY(),
                inputs.taaClipScale(),
                inputs.taaRenderScale(),
                inputs.taaLumaClipEnabled(),
                inputs.taaSharpenStrength(),
                inputs.reflectionsEnabled(),
                inputs.reflectionsMode(),
                inputs.planarTimestampQueryPool(),
                inputs.planarTimestampQueryStartIndex(),
                inputs.planarTimestampQueryEndIndex(),
                inputs.reflectionsSsrStrength(),
                inputs.reflectionsSsrMaxRoughness(),
                inputs.reflectionsSsrStepScale(),
                inputs.reflectionsTemporalWeight(),
                inputs.reflectionsPlanarStrength(),
                inputs.reflectionsPlanarPlaneHeight(),
                inputs.reflectionsRtDenoiseStrength(),
                inputs.taaDebugView(),
                inputs.postRenderPass(),
                inputs.postGraphicsPipeline(),
                inputs.postPipelineLayout(),
                inputs.postDescriptorSet(),
                inputs.offscreenColorImage(),
                inputs.taaHistoryImage(),
                inputs.taaHistoryVelocityImage(),
                inputs.planarCaptureImage(),
                inputs.velocityImage(),
                inputs.depthImages(),
                inputs.swapchainImages(),
                inputs.postFramebuffers(),
                inputs.descriptorSetForFrame(),
                inputs.dynamicUniformOffset(),
                inputs.vkFailure()
        );
    }

    public static VulkanFrameCommandOrchestrator.Inputs create(
            CommonInputs common,
            PostInputs post,
            VulkanFrameCommandOrchestrator.LongByInt descriptorSetForFrame,
            IntUnaryOperator dynamicUniformOffset,
            VulkanFrameCommandOrchestrator.FailureFactory vkFailure
    ) {
        return new VulkanFrameCommandOrchestrator.Inputs(
                common.gpuMeshes(),
                common.instanceBatches(),
                common.indirectDrawBuffer(),
                common.drawMetaBuffer(),
                common.cullingComputePass(),
                common.viewProjMatrix(),
                common.bindlessActive(),
                common.bindlessDescriptorSet(),
                common.bindlessDescriptorHeap(),
                common.maxDynamicSceneObjects(),
                common.swapchainWidth(),
                common.swapchainHeight(),
                common.swapchainImageFormat(),
                common.depthFormat(),
                common.shadowMapResolution(),
                common.shadowEnabled(),
                common.pointShadowEnabled(),
                common.shadowCascadeCount(),
                common.maxShadowMatrices(),
                common.maxShadowCascades(),
                common.pointShadowFaces(),
                common.renderPass(),
                common.framebuffers(),
                common.mainGeometryPipeline(),
                common.mainGeometryPipelineLayout(),
                common.mainGeometryBindlessStaticPipeline(),
                common.mainGeometryBindlessStaticPipelineLayout(),
                common.mainGeometryBindlessSkinnedPipeline(),
                common.mainGeometryBindlessSkinnedPipelineLayout(),
                common.mainGeometryBindlessMorphPipeline(),
                common.mainGeometryBindlessMorphPipelineLayout(),
                common.mainGeometryBindlessSkinnedMorphPipeline(),
                common.mainGeometryBindlessSkinnedMorphPipelineLayout(),
                common.mainGeometryBindlessInstancedPipeline(),
                common.mainGeometryBindlessInstancedPipelineLayout(),
                common.mainGeometryMorphPipeline(),
                common.mainGeometryMorphPipelineLayout(),
                common.mainGeometrySkinnedPipeline(),
                common.mainGeometrySkinnedPipelineLayout(),
                common.mainGeometrySkinnedMorphPipeline(),
                common.mainGeometrySkinnedMorphPipelineLayout(),
                common.mainGeometryInstancedPipeline(),
                common.mainGeometryInstancedPipelineLayout(),
                common.shadowRenderPass(),
                common.shadowPipeline(),
                common.shadowInstancedPipeline(),
                common.shadowBindlessInstancedPipeline(),
                common.shadowPipelineLayout(),
                common.shadowFramebuffers(),
                common.shadowDepthImage(),
                common.shadowMomentImage(),
                common.shadowMomentFormat(),
                common.shadowMomentMipLevels(),
                common.shadowMomentPipelineRequested(),
                common.shadowMomentInitialized(),
                post.postOffscreenActive(),
                post.postIntermediateInitialized(),
                post.tonemapEnabled(),
                post.tonemapExposure(),
                post.tonemapGamma(),
                post.ssaoEnabled(),
                post.bloomEnabled(),
                post.bloomThreshold(),
                post.bloomStrength(),
                post.ssaoStrength(),
                post.ssaoRadius(),
                post.ssaoBias(),
                post.ssaoPower(),
                post.smaaEnabled(),
                post.smaaStrength(),
                post.taaEnabled(),
                post.taaBlend(),
                post.taaHistoryInitialized(),
                post.taaJitterUvDeltaX(),
                post.taaJitterUvDeltaY(),
                post.taaMotionUvX(),
                post.taaMotionUvY(),
                post.taaClipScale(),
                post.taaRenderScale(),
                post.taaLumaClipEnabled(),
                post.taaSharpenStrength(),
                post.reflectionsEnabled(),
                post.reflectionsMode(),
                common.planarTimestampQueryPool(),
                common.planarTimestampQueryStartIndex(),
                common.planarTimestampQueryEndIndex(),
                post.reflectionsSsrStrength(),
                post.reflectionsSsrMaxRoughness(),
                post.reflectionsSsrStepScale(),
                post.reflectionsTemporalWeight(),
                post.reflectionsPlanarStrength(),
                post.reflectionsPlanarPlaneHeight(),
                post.reflectionsRtDenoiseStrength(),
                post.taaDebugView(),
                post.postRenderPass(),
                post.postGraphicsPipeline(),
                post.postPipelineLayout(),
                post.postDescriptorSet(),
                post.offscreenColorImage(),
                post.taaHistoryImage(),
                post.taaHistoryVelocityImage(),
                post.planarCaptureImage(),
                post.velocityImage(),
                common.depthImages(),
                post.swapchainImages(),
                post.postFramebuffers(),
                descriptorSetForFrame,
                dynamicUniformOffset,
                vkFailure
        );
    }

    public record Inputs(
            List<VulkanGpuMesh> gpuMeshes,
            List<VulkanInstanceBatch> instanceBatches,
            VulkanIndirectDrawBuffer indirectDrawBuffer,
            VulkanDrawMetaBuffer drawMetaBuffer,
            VulkanCullingComputePass cullingComputePass,
            float[] viewProjMatrix,
            boolean bindlessActive,
            long bindlessDescriptorSet,
            VulkanBindlessDescriptorHeap bindlessDescriptorHeap,
            int maxDynamicSceneObjects,
            int swapchainWidth,
            int swapchainHeight,
            int swapchainImageFormat,
            int depthFormat,
            int shadowMapResolution,
            boolean shadowEnabled,
            boolean pointShadowEnabled,
            int shadowCascadeCount,
            int maxShadowMatrices,
            int maxShadowCascades,
            int pointShadowFaces,
            long renderPass,
            long[] framebuffers,
            long mainGeometryPipeline,
            long mainGeometryPipelineLayout,
            long mainGeometryBindlessStaticPipeline,
            long mainGeometryBindlessStaticPipelineLayout,
            long mainGeometryBindlessSkinnedPipeline,
            long mainGeometryBindlessSkinnedPipelineLayout,
            long mainGeometryBindlessMorphPipeline,
            long mainGeometryBindlessMorphPipelineLayout,
            long mainGeometryBindlessSkinnedMorphPipeline,
            long mainGeometryBindlessSkinnedMorphPipelineLayout,
            long mainGeometryBindlessInstancedPipeline,
            long mainGeometryBindlessInstancedPipelineLayout,
            long mainGeometryMorphPipeline,
            long mainGeometryMorphPipelineLayout,
            long mainGeometrySkinnedPipeline,
            long mainGeometrySkinnedPipelineLayout,
            long mainGeometrySkinnedMorphPipeline,
            long mainGeometrySkinnedMorphPipelineLayout,
            long mainGeometryInstancedPipeline,
            long mainGeometryInstancedPipelineLayout,
            long shadowRenderPass,
            long shadowPipeline,
            long shadowInstancedPipeline,
            long shadowBindlessInstancedPipeline,
            long shadowPipelineLayout,
            long[] shadowFramebuffers,
            long shadowDepthImage,
            long shadowMomentImage,
            int shadowMomentFormat,
            int shadowMomentMipLevels,
            boolean shadowMomentPipelineRequested,
            boolean shadowMomentInitialized,
            long planarTimestampQueryPool,
            int planarTimestampQueryStartIndex,
            int planarTimestampQueryEndIndex,
            boolean postOffscreenActive,
            boolean postIntermediateInitialized,
            boolean tonemapEnabled,
            float tonemapExposure,
            float tonemapGamma,
            boolean ssaoEnabled,
            boolean bloomEnabled,
            float bloomThreshold,
            float bloomStrength,
            float ssaoStrength,
            float ssaoRadius,
            float ssaoBias,
            float ssaoPower,
            boolean smaaEnabled,
            float smaaStrength,
            boolean taaEnabled,
            float taaBlend,
            boolean taaHistoryInitialized,
            float taaJitterUvDeltaX,
            float taaJitterUvDeltaY,
            float taaMotionUvX,
            float taaMotionUvY,
            float taaClipScale,
            float taaRenderScale,
            boolean taaLumaClipEnabled,
            float taaSharpenStrength,
            boolean reflectionsEnabled,
            int reflectionsMode,
            float reflectionsSsrStrength,
            float reflectionsSsrMaxRoughness,
            float reflectionsSsrStepScale,
            float reflectionsTemporalWeight,
            float reflectionsPlanarStrength,
            float reflectionsPlanarPlaneHeight,
            float reflectionsRtDenoiseStrength,
            int taaDebugView,
            long postRenderPass,
            long postGraphicsPipeline,
            long postPipelineLayout,
            long postDescriptorSet,
            long offscreenColorImage,
            long taaHistoryImage,
            long taaHistoryVelocityImage,
            long planarCaptureImage,
            long velocityImage,
            long[] depthImages,
            long[] swapchainImages,
            long[] postFramebuffers,
            VulkanFrameCommandOrchestrator.LongByInt descriptorSetForFrame,
            IntUnaryOperator dynamicUniformOffset,
            VulkanFrameCommandOrchestrator.FailureFactory vkFailure
    ) {
    }

    public record CommonInputs(
            List<VulkanGpuMesh> gpuMeshes,
            List<VulkanInstanceBatch> instanceBatches,
            VulkanIndirectDrawBuffer indirectDrawBuffer,
            VulkanDrawMetaBuffer drawMetaBuffer,
            VulkanCullingComputePass cullingComputePass,
            float[] viewProjMatrix,
            boolean bindlessActive,
            long bindlessDescriptorSet,
            VulkanBindlessDescriptorHeap bindlessDescriptorHeap,
            int maxDynamicSceneObjects,
            int swapchainWidth,
            int swapchainHeight,
            int swapchainImageFormat,
            int depthFormat,
            int shadowMapResolution,
            boolean shadowEnabled,
            boolean pointShadowEnabled,
            int shadowCascadeCount,
            int maxShadowMatrices,
            int maxShadowCascades,
            int pointShadowFaces,
            long renderPass,
            long[] framebuffers,
            long mainGeometryPipeline,
            long mainGeometryPipelineLayout,
            long mainGeometryBindlessStaticPipeline,
            long mainGeometryBindlessStaticPipelineLayout,
            long mainGeometryBindlessSkinnedPipeline,
            long mainGeometryBindlessSkinnedPipelineLayout,
            long mainGeometryBindlessMorphPipeline,
            long mainGeometryBindlessMorphPipelineLayout,
            long mainGeometryBindlessSkinnedMorphPipeline,
            long mainGeometryBindlessSkinnedMorphPipelineLayout,
            long mainGeometryBindlessInstancedPipeline,
            long mainGeometryBindlessInstancedPipelineLayout,
            long mainGeometryMorphPipeline,
            long mainGeometryMorphPipelineLayout,
            long mainGeometrySkinnedPipeline,
            long mainGeometrySkinnedPipelineLayout,
            long mainGeometrySkinnedMorphPipeline,
            long mainGeometrySkinnedMorphPipelineLayout,
            long mainGeometryInstancedPipeline,
            long mainGeometryInstancedPipelineLayout,
            long shadowRenderPass,
            long shadowPipeline,
            long shadowInstancedPipeline,
            long shadowBindlessInstancedPipeline,
            long shadowPipelineLayout,
            long[] shadowFramebuffers,
            long shadowDepthImage,
            long shadowMomentImage,
            int shadowMomentFormat,
            int shadowMomentMipLevels,
            boolean shadowMomentPipelineRequested,
            boolean shadowMomentInitialized,
            long[] depthImages,
            long planarTimestampQueryPool,
            int planarTimestampQueryStartIndex,
            int planarTimestampQueryEndIndex
    ) {
    }

    public record PostInputs(
            boolean postOffscreenActive,
            boolean postIntermediateInitialized,
            boolean tonemapEnabled,
            float tonemapExposure,
            float tonemapGamma,
            boolean ssaoEnabled,
            boolean bloomEnabled,
            float bloomThreshold,
            float bloomStrength,
            float ssaoStrength,
            float ssaoRadius,
            float ssaoBias,
            float ssaoPower,
            boolean smaaEnabled,
            float smaaStrength,
            boolean taaEnabled,
            float taaBlend,
            boolean taaHistoryInitialized,
            float taaJitterUvDeltaX,
            float taaJitterUvDeltaY,
            float taaMotionUvX,
            float taaMotionUvY,
            float taaClipScale,
            float taaRenderScale,
            boolean taaLumaClipEnabled,
            float taaSharpenStrength,
            boolean reflectionsEnabled,
            int reflectionsMode,
            float reflectionsSsrStrength,
            float reflectionsSsrMaxRoughness,
            float reflectionsSsrStepScale,
            float reflectionsTemporalWeight,
            float reflectionsPlanarStrength,
            float reflectionsPlanarPlaneHeight,
            float reflectionsRtDenoiseStrength,
            int taaDebugView,
            long postRenderPass,
            long postGraphicsPipeline,
            long postPipelineLayout,
            long postDescriptorSet,
            long offscreenColorImage,
            long taaHistoryImage,
            long taaHistoryVelocityImage,
            long planarCaptureImage,
            long velocityImage,
            long[] swapchainImages,
            long[] postFramebuffers
    ) {
    }
}
