package org.dynamislight.impl.vulkan.command;

import java.util.List;
import java.util.function.IntUnaryOperator;

import org.dynamislight.impl.vulkan.model.VulkanGpuMesh;
import org.dynamislight.impl.vulkan.model.VulkanInstanceBatch;

public final class VulkanFrameCommandInputAssembler {
    private VulkanFrameCommandInputAssembler() {
    }

    public static VulkanFrameCommandOrchestrator.Inputs build(AssemblyInputs in) {
        return VulkanFrameCommandInputsFactory.create(
                new VulkanFrameCommandInputsFactory.Inputs(
                        in.gpuMeshes(),
                        in.instanceBatches(),
                        in.indirectDrawBuffer(),
                        in.drawMetaBuffer(),
                        in.cullingComputePass(),
                        in.viewProjMatrix(),
                        in.bindlessActive(),
                        in.bindlessDescriptorSet(),
                        in.bindlessDescriptorHeap(),
                        in.maxDynamicSceneObjects(),
                        in.swapchainWidth(),
                        in.swapchainHeight(),
                        in.swapchainImageFormat(),
                        in.depthFormat(),
                        in.shadowMapResolution(),
                        in.shadowEnabled(),
                        in.pointShadowEnabled(),
                        in.shadowCascadeCount(),
                        in.maxShadowMatrices(),
                        in.maxShadowCascades(),
                        in.pointShadowFaces(),
                        in.renderPass(),
                        in.framebuffers(),
                        in.mainGeometryPipeline(),
                        in.mainGeometryPipelineLayout(),
                        in.mainGeometryBindlessStaticPipeline(),
                        in.mainGeometryBindlessStaticPipelineLayout(),
                        in.mainGeometryBindlessSkinnedPipeline(),
                        in.mainGeometryBindlessSkinnedPipelineLayout(),
                        in.mainGeometryBindlessMorphPipeline(),
                        in.mainGeometryBindlessMorphPipelineLayout(),
                        in.mainGeometryBindlessSkinnedMorphPipeline(),
                        in.mainGeometryBindlessSkinnedMorphPipelineLayout(),
                        in.mainGeometryMorphPipeline(),
                        in.mainGeometryMorphPipelineLayout(),
                        in.mainGeometrySkinnedPipeline(),
                        in.mainGeometrySkinnedPipelineLayout(),
                        in.mainGeometrySkinnedMorphPipeline(),
                        in.mainGeometrySkinnedMorphPipelineLayout(),
                        in.mainGeometryInstancedPipeline(),
                        in.mainGeometryInstancedPipelineLayout(),
                        in.shadowRenderPass(),
                        in.shadowPipeline(),
                        in.shadowInstancedPipeline(),
                        in.shadowPipelineLayout(),
                        in.shadowFramebuffers(),
                        in.shadowDepthImage(),
                        in.shadowMomentImage(),
                        in.shadowMomentFormat(),
                        in.shadowMomentMipLevels(),
                        in.shadowMomentPipelineRequested(),
                        in.shadowMomentInitialized(),
                        in.planarTimestampQueryPool(),
                        in.planarTimestampQueryStartIndex(),
                        in.planarTimestampQueryEndIndex(),
                        in.postOffscreenActive(),
                        in.postIntermediateInitialized(),
                        in.tonemapEnabled(),
                        in.tonemapExposure(),
                        in.tonemapGamma(),
                        in.ssaoEnabled(),
                        in.bloomEnabled(),
                        in.bloomThreshold(),
                        in.bloomStrength(),
                        in.ssaoStrength(),
                        in.ssaoRadius(),
                        in.ssaoBias(),
                        in.ssaoPower(),
                        in.smaaEnabled(),
                        in.smaaStrength(),
                        in.taaEnabled(),
                        in.taaBlend(),
                        in.taaHistoryInitialized(),
                        in.taaJitterUvDeltaX(),
                        in.taaJitterUvDeltaY(),
                        in.taaMotionUvX(),
                        in.taaMotionUvY(),
                        in.taaClipScale(),
                        in.taaRenderScale(),
                        in.taaLumaClipEnabled(),
                        in.taaSharpenStrength(),
                        in.reflectionsEnabled(),
                        in.reflectionsMode(),
                        in.reflectionsSsrStrength(),
                        in.reflectionsSsrMaxRoughness(),
                        in.reflectionsSsrStepScale(),
                        in.reflectionsTemporalWeight(),
                        in.reflectionsPlanarStrength(),
                        in.reflectionsPlanarPlaneHeight(),
                        in.reflectionsRtDenoiseStrength(),
                        in.taaDebugView(),
                        in.postRenderPass(),
                        in.postGraphicsPipeline(),
                        in.postPipelineLayout(),
                        in.postDescriptorSet(),
                        in.offscreenColorImage(),
                        in.taaHistoryImage(),
                        in.taaHistoryVelocityImage(),
                        in.planarCaptureImage(),
                        in.velocityImage(),
                        in.depthImages(),
                        in.swapchainImages(),
                        in.postFramebuffers(),
                        in.descriptorSetForFrame(),
                        in.dynamicUniformOffsetForMesh(),
                        in.vkFailure()
                )
        );
    }

    public record AssemblyInputs(
            List<VulkanGpuMesh> gpuMeshes,
            List<VulkanInstanceBatch> instanceBatches,
            VulkanIndirectDrawBuffer indirectDrawBuffer,
            VulkanDrawMetaBuffer drawMetaBuffer,
            VulkanCullingComputePass cullingComputePass,
            float[] viewProjMatrix,
            boolean bindlessActive,
            long bindlessDescriptorSet,
            VulkanBindlessDescriptorHeap bindlessDescriptorHeap,
            int maxDynamicSceneObjects,
            int swapchainWidth,
            int swapchainHeight,
            int swapchainImageFormat,
            int depthFormat,
            int shadowMapResolution,
            boolean shadowEnabled,
            boolean pointShadowEnabled,
            int shadowCascadeCount,
            int maxShadowMatrices,
            int maxShadowCascades,
            int pointShadowFaces,
            long renderPass,
            long[] framebuffers,
            long mainGeometryPipeline,
            long mainGeometryPipelineLayout,
            long mainGeometryBindlessStaticPipeline,
            long mainGeometryBindlessStaticPipelineLayout,
            long mainGeometryBindlessSkinnedPipeline,
            long mainGeometryBindlessSkinnedPipelineLayout,
            long mainGeometryBindlessMorphPipeline,
            long mainGeometryBindlessMorphPipelineLayout,
            long mainGeometryBindlessSkinnedMorphPipeline,
            long mainGeometryBindlessSkinnedMorphPipelineLayout,
            long mainGeometryMorphPipeline,
            long mainGeometryMorphPipelineLayout,
            long mainGeometrySkinnedPipeline,
            long mainGeometrySkinnedPipelineLayout,
            long mainGeometrySkinnedMorphPipeline,
            long mainGeometrySkinnedMorphPipelineLayout,
            long mainGeometryInstancedPipeline,
            long mainGeometryInstancedPipelineLayout,
            long shadowRenderPass,
            long shadowPipeline,
            long shadowInstancedPipeline,
            long shadowPipelineLayout,
            long[] shadowFramebuffers,
            long shadowDepthImage,
            long shadowMomentImage,
            int shadowMomentFormat,
            int shadowMomentMipLevels,
            boolean shadowMomentPipelineRequested,
            boolean shadowMomentInitialized,
            long[] depthImages,
            long planarTimestampQueryPool,
            int planarTimestampQueryStartIndex,
            int planarTimestampQueryEndIndex,
            boolean postOffscreenActive,
            boolean postIntermediateInitialized,
            boolean tonemapEnabled,
            float tonemapExposure,
            float tonemapGamma,
            boolean ssaoEnabled,
            boolean bloomEnabled,
            float bloomThreshold,
            float bloomStrength,
            float ssaoStrength,
            float ssaoRadius,
            float ssaoBias,
            float ssaoPower,
            boolean smaaEnabled,
            float smaaStrength,
            boolean taaEnabled,
            float taaBlend,
            boolean taaHistoryInitialized,
            float taaJitterUvDeltaX,
            float taaJitterUvDeltaY,
            float taaMotionUvX,
            float taaMotionUvY,
            float taaClipScale,
            float taaRenderScale,
            boolean taaLumaClipEnabled,
            float taaSharpenStrength,
            boolean reflectionsEnabled,
            int reflectionsMode,
            float reflectionsSsrStrength,
            float reflectionsSsrMaxRoughness,
            float reflectionsSsrStepScale,
            float reflectionsTemporalWeight,
            float reflectionsPlanarStrength,
            float reflectionsPlanarPlaneHeight,
            float reflectionsRtDenoiseStrength,
            int taaDebugView,
            long postRenderPass,
            long postGraphicsPipeline,
            long postPipelineLayout,
            long postDescriptorSet,
            long offscreenColorImage,
            long taaHistoryImage,
            long taaHistoryVelocityImage,
            long planarCaptureImage,
            long velocityImage,
            long[] swapchainImages,
            long[] postFramebuffers,
            VulkanFrameCommandOrchestrator.LongByInt descriptorSetForFrame,
            IntUnaryOperator dynamicUniformOffsetForMesh,
            VulkanFrameCommandOrchestrator.FailureFactory vkFailure
    ) {
    }
}
