package org.dynamislight.impl.vulkan.command;

import java.util.List;
import java.util.function.IntUnaryOperator;
import org.dynamislight.impl.vulkan.model.VulkanGpuMesh;

public final class VulkanFrameCommandInputsFactory {
    private VulkanFrameCommandInputsFactory() {
    }

    public static VulkanFrameCommandOrchestrator.Inputs create(Inputs inputs) {
        return new VulkanFrameCommandOrchestrator.Inputs(
                inputs.gpuMeshes(),
                inputs.maxDynamicSceneObjects(),
                inputs.swapchainWidth(),
                inputs.swapchainHeight(),
                inputs.shadowMapResolution(),
                inputs.shadowEnabled(),
                inputs.pointShadowEnabled(),
                inputs.shadowCascadeCount(),
                inputs.maxShadowMatrices(),
                inputs.maxShadowCascades(),
                inputs.pointShadowFaces(),
                inputs.renderPass(),
                inputs.framebuffers(),
                inputs.graphicsPipeline(),
                inputs.pipelineLayout(),
                inputs.shadowRenderPass(),
                inputs.shadowPipeline(),
                inputs.shadowPipelineLayout(),
                inputs.shadowFramebuffers(),
                inputs.postOffscreenActive(),
                inputs.postIntermediateInitialized(),
                inputs.tonemapEnabled(),
                inputs.tonemapExposure(),
                inputs.tonemapGamma(),
                inputs.ssaoEnabled(),
                inputs.bloomEnabled(),
                inputs.bloomThreshold(),
                inputs.bloomStrength(),
                inputs.ssaoStrength(),
                inputs.ssaoRadius(),
                inputs.ssaoBias(),
                inputs.ssaoPower(),
                inputs.smaaEnabled(),
                inputs.smaaStrength(),
                inputs.taaEnabled(),
                inputs.taaBlend(),
                inputs.taaHistoryInitialized(),
                inputs.taaJitterUvDeltaX(),
                inputs.taaJitterUvDeltaY(),
                inputs.taaMotionUvX(),
                inputs.taaMotionUvY(),
                inputs.taaDebugView(),
                inputs.postRenderPass(),
                inputs.postGraphicsPipeline(),
                inputs.postPipelineLayout(),
                inputs.postDescriptorSet(),
                inputs.offscreenColorImage(),
                inputs.taaHistoryImage(),
                inputs.velocityImage(),
                inputs.swapchainImages(),
                inputs.postFramebuffers(),
                inputs.descriptorSetForFrame(),
                inputs.dynamicUniformOffset(),
                inputs.vkFailure()
        );
    }

    public static VulkanFrameCommandOrchestrator.Inputs create(
            CommonInputs common,
            PostInputs post,
            VulkanFrameCommandOrchestrator.LongByInt descriptorSetForFrame,
            IntUnaryOperator dynamicUniformOffset,
            VulkanFrameCommandOrchestrator.FailureFactory vkFailure
    ) {
        return new VulkanFrameCommandOrchestrator.Inputs(
                common.gpuMeshes(),
                common.maxDynamicSceneObjects(),
                common.swapchainWidth(),
                common.swapchainHeight(),
                common.shadowMapResolution(),
                common.shadowEnabled(),
                common.pointShadowEnabled(),
                common.shadowCascadeCount(),
                common.maxShadowMatrices(),
                common.maxShadowCascades(),
                common.pointShadowFaces(),
                common.renderPass(),
                common.framebuffers(),
                common.graphicsPipeline(),
                common.pipelineLayout(),
                common.shadowRenderPass(),
                common.shadowPipeline(),
                common.shadowPipelineLayout(),
                common.shadowFramebuffers(),
                post.postOffscreenActive(),
                post.postIntermediateInitialized(),
                post.tonemapEnabled(),
                post.tonemapExposure(),
                post.tonemapGamma(),
                post.ssaoEnabled(),
                post.bloomEnabled(),
                post.bloomThreshold(),
                post.bloomStrength(),
                post.ssaoStrength(),
                post.ssaoRadius(),
                post.ssaoBias(),
                post.ssaoPower(),
                post.smaaEnabled(),
                post.smaaStrength(),
                post.taaEnabled(),
                post.taaBlend(),
                post.taaHistoryInitialized(),
                post.taaJitterUvDeltaX(),
                post.taaJitterUvDeltaY(),
                post.taaMotionUvX(),
                post.taaMotionUvY(),
                post.taaDebugView(),
                post.postRenderPass(),
                post.postGraphicsPipeline(),
                post.postPipelineLayout(),
                post.postDescriptorSet(),
                post.offscreenColorImage(),
                post.taaHistoryImage(),
                post.velocityImage(),
                post.swapchainImages(),
                post.postFramebuffers(),
                descriptorSetForFrame,
                dynamicUniformOffset,
                vkFailure
        );
    }

    public record Inputs(
            List<VulkanGpuMesh> gpuMeshes,
            int maxDynamicSceneObjects,
            int swapchainWidth,
            int swapchainHeight,
            int shadowMapResolution,
            boolean shadowEnabled,
            boolean pointShadowEnabled,
            int shadowCascadeCount,
            int maxShadowMatrices,
            int maxShadowCascades,
            int pointShadowFaces,
            long renderPass,
            long[] framebuffers,
            long graphicsPipeline,
            long pipelineLayout,
            long shadowRenderPass,
            long shadowPipeline,
            long shadowPipelineLayout,
            long[] shadowFramebuffers,
            boolean postOffscreenActive,
            boolean postIntermediateInitialized,
            boolean tonemapEnabled,
            float tonemapExposure,
            float tonemapGamma,
            boolean ssaoEnabled,
            boolean bloomEnabled,
            float bloomThreshold,
            float bloomStrength,
            float ssaoStrength,
            float ssaoRadius,
            float ssaoBias,
            float ssaoPower,
            boolean smaaEnabled,
            float smaaStrength,
            boolean taaEnabled,
            float taaBlend,
            boolean taaHistoryInitialized,
            float taaJitterUvDeltaX,
            float taaJitterUvDeltaY,
            float taaMotionUvX,
            float taaMotionUvY,
            int taaDebugView,
            long postRenderPass,
            long postGraphicsPipeline,
            long postPipelineLayout,
            long postDescriptorSet,
            long offscreenColorImage,
            long taaHistoryImage,
            long velocityImage,
            long[] swapchainImages,
            long[] postFramebuffers,
            VulkanFrameCommandOrchestrator.LongByInt descriptorSetForFrame,
            IntUnaryOperator dynamicUniformOffset,
            VulkanFrameCommandOrchestrator.FailureFactory vkFailure
    ) {
    }

    public record CommonInputs(
            List<VulkanGpuMesh> gpuMeshes,
            int maxDynamicSceneObjects,
            int swapchainWidth,
            int swapchainHeight,
            int shadowMapResolution,
            boolean shadowEnabled,
            boolean pointShadowEnabled,
            int shadowCascadeCount,
            int maxShadowMatrices,
            int maxShadowCascades,
            int pointShadowFaces,
            long renderPass,
            long[] framebuffers,
            long graphicsPipeline,
            long pipelineLayout,
            long shadowRenderPass,
            long shadowPipeline,
            long shadowPipelineLayout,
            long[] shadowFramebuffers
    ) {
    }

    public record PostInputs(
            boolean postOffscreenActive,
            boolean postIntermediateInitialized,
            boolean tonemapEnabled,
            float tonemapExposure,
            float tonemapGamma,
            boolean ssaoEnabled,
            boolean bloomEnabled,
            float bloomThreshold,
            float bloomStrength,
            float ssaoStrength,
            float ssaoRadius,
            float ssaoBias,
            float ssaoPower,
            boolean smaaEnabled,
            float smaaStrength,
            boolean taaEnabled,
            float taaBlend,
            boolean taaHistoryInitialized,
            float taaJitterUvDeltaX,
            float taaJitterUvDeltaY,
            float taaMotionUvX,
            float taaMotionUvY,
            int taaDebugView,
            long postRenderPass,
            long postGraphicsPipeline,
            long postPipelineLayout,
            long postDescriptorSet,
            long offscreenColorImage,
            long taaHistoryImage,
            long velocityImage,
            long[] swapchainImages,
            long[] postFramebuffers
    ) {
    }
}
