package org.dynamislight.api.runtime;

import org.dynamislight.api.error.EngineErrorReport;
import org.dynamislight.api.event.EngineEvent;
import org.dynamislight.api.logging.LogMessage;

/**
 * A callback interface for handling various events, logs, errors, and optional
 * rendering frame updates that occur during the lifecycle of the engine runtime.
 * Implementations of this interface enable host applications to react to engine
 * state changes, log messages, error notifications, and rendering progress.
 *
 * Methods:
 * - {@code onEvent(EngineEvent event)}: Invoked for significant engine events, such as
 *   scene loading, resource reloading, device loss, or runtime warnings. This allows
 *   the host to handle key updates or state transitions.
 *
 * - {@code onLog(LogMessage message)}: Called when a new log message is generated by
 *   the engine, providing diagnostic or informational messages typically paired with
 *   a severity level and category.
 *
 * - {@code onError(EngineErrorReport error)}: Triggered when an error occurs within
 *   the engine runtime, allowing the host to perform custom error handling or recovery
 *   actions based on the detailed error report.
 *
 * - {@code onFrameReady(FrameHandle frame)} (optional): Called when a rendered frame
 *   is ready, primarily used in scenarios like embedding in external previews or
 *   rendering workflows. This method has a default empty implementation and can be
 *   optionally overridden.
 */
public interface EngineHostCallbacks {
    /**
     * Invoked when a significant engine event occurs during the runtime lifecycle.
     * This method serves as a callback mechanism, allowing host applications to
     * respond to various state changes or operational updates within the engine.
     *
     * Potential events include scene-related changes, resource updates,
     * device events, or performance warnings, each represented by a specific
     * {@link EngineEvent} implementation.
     *
     * @param event the engine event being reported; never null. The specific type
     *              of the event determines the context and additional information
     *              available for handling the occurrence.
     */
    void onEvent(EngineEvent event);

    /**
     * Called when a new log message is generated by the engine.
     *
     * This method enables host applications to handle diagnostic or informational
     * log messages provided by the engine during its runtime. The {@link LogMessage}
     * object contains relevant metadata, including the severity level, category,
     * message content, and timestamp.
     *
     * @param message the log message containing details about the event; never null
     */
    void onLog(LogMessage message);

    /**
     * Triggered when an error occurs within the engine runtime, providing a
     * mechanism for custom error handling or recovery.
     *
     * The {@link EngineErrorReport} contains detailed information about the error,
     * including its type, description, recoverability, and any underlying cause.
     * Implementations of this method can use the provided error report to log
     * errors, alert users, or perform recovery steps, depending on the specific
     * context.
     *
     * @param error the detailed report of the engine-related error; never null. This
     *              report provides information on the error code, message, recoverability,
     *              and optional cause, helping the host understand and respond to the issue.
     */
    void onError(EngineErrorReport error);

    /**
     * Called when a new frame is ready during the engine's rendering workflow.
     *
     * This method serves as a hook for host applications to handle or process
     * the rendered frame. It is particularly useful for embedding or preview-related
     * workflows where frames need to be inspected, captured, or forwarded.
     *
     * @param frame the frame handle representing the rendered output; never null.
     *              The handle remains valid until the next render call unless its
     *              {@code persistent} property is set to {@code true}.
     */
    default void onFrameReady(FrameHandle frame) {
        // Optional callback for embedding/preview workflows.
    }
}
