#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

SOURCE_DIR_INPUT="${1:-artifacts/compare}"
SOURCE_DIR="$SOURCE_DIR_INPUT"
OUT_DIR="${2:-artifacts/compare/threshold-lock}"
MIN_RUNS="${DLE_COMPARE_THRESHOLD_LOCK_MIN_RUNS:-3}"
mkdir -p "$OUT_DIR"

resolve_source_dir() {
  local requested="$1"
  local candidate_a="$requested"
  local candidate_b="engine-host-sample/$requested"
  if [[ -d "$candidate_a" ]] && find "$candidate_a" -type f -name 'compare-metadata.properties' -print -quit | grep -q .; then
    printf '%s\n' "$candidate_a"
    return 0
  fi
  if [[ -d "$candidate_b" ]] && find "$candidate_b" -type f -name 'compare-metadata.properties' -print -quit | grep -q .; then
    printf '%s\n' "$candidate_b"
    return 0
  fi
  if [[ -d "$candidate_a" ]]; then
    printf '%s\n' "$candidate_a"
    return 0
  fi
  if [[ -d "$candidate_b" ]]; then
    printf '%s\n' "$candidate_b"
    return 0
  fi
  return 1
}

if ! SOURCE_DIR="$(resolve_source_dir "$SOURCE_DIR")"; then
  echo "No compare source directory found for: $SOURCE_DIR_INPUT" >&2
  echo "Tried: '$SOURCE_DIR_INPUT' and 'engine-host-sample/$SOURCE_DIR_INPUT'" >&2
  exit 1
fi

TMP_INPUT="$(mktemp -t dle-aa-lock-input.XXXXXX.tsv)"
trap 'rm -f "$TMP_INPUT"' EXIT

while IFS= read -r meta; do
  mode="$(sed -n 's/^compare\.vulkan\.mode=//p' "$meta" | tail -n1)"
  profile="$(sed -n 's/^compare\.profileTag=//p' "$meta" | tail -n1)"
  diff="$(sed -n 's/^compare\.diffMetric=//p' "$meta" | tail -n1)"
  og_shimmer="$(sed -n 's/^compare\.opengl\.shimmerIndex=//p' "$meta" | tail -n1)"
  vk_shimmer="$(sed -n 's/^compare\.vulkan\.shimmerIndex=//p' "$meta" | tail -n1)"
  og_reject="$(sed -n 's/^compare\.opengl\.taaHistoryRejectRate=//p' "$meta" | tail -n1)"
  vk_reject="$(sed -n 's/^compare\.vulkan\.taaHistoryRejectRate=//p' "$meta" | tail -n1)"
  og_conf="$(sed -n 's/^compare\.opengl\.taaConfidenceMean=//p' "$meta" | tail -n1)"
  vk_conf="$(sed -n 's/^compare\.vulkan\.taaConfidenceMean=//p' "$meta" | tail -n1)"
  og_reject_window="$(sed -n 's/^compare\.opengl\.taaRejectTrendWindow=//p' "$meta" | tail -n1)"
  vk_reject_window="$(sed -n 's/^compare\.vulkan\.taaRejectTrendWindow=//p' "$meta" | tail -n1)"
  og_conf_window="$(sed -n 's/^compare\.opengl\.taaConfidenceTrendWindow=//p' "$meta" | tail -n1)"
  vk_conf_window="$(sed -n 's/^compare\.vulkan\.taaConfidenceTrendWindow=//p' "$meta" | tail -n1)"
  og_drop_window="$(sed -n 's/^compare\.opengl\.taaConfidenceDropWindow=//p' "$meta" | tail -n1)"
  vk_drop_window="$(sed -n 's/^compare\.vulkan\.taaConfidenceDropWindow=//p' "$meta" | tail -n1)"
  if [[ -z "$mode" || -z "$profile" || -z "$diff" ]]; then
    continue
  fi
  if [[ "$mode" != "vulkan_real" ]]; then
    continue
  fi
  echo -e "${profile}\t${diff}\t${og_shimmer:-0}\t${vk_shimmer:-0}\t${og_reject:-0}\t${vk_reject:-0}\t${og_conf:-0}\t${vk_conf:-0}\t${og_reject_window:-0}\t${vk_reject_window:-0}\t${og_conf_window:-0}\t${vk_conf_window:-0}\t${og_drop_window:-0}\t${vk_drop_window:-0}" >> "$TMP_INPUT"
done < <(find "$SOURCE_DIR" -type f -name 'compare-metadata.properties' 2>/dev/null | sort)

if [[ ! -s "$TMP_INPUT" ]]; then
  echo "No real Vulkan compare metadata found under: $SOURCE_DIR" >&2
  exit 1
fi

REPORT_TSV="$OUT_DIR/threshold-lock-report.tsv"
RECOMMENDED_PROPS="$OUT_DIR/recommended-thresholds.properties"

awk -F'\t' -v min_runs="${MIN_RUNS}" '
function abs(x) { return x < 0 ? -x : x }
{
  p = $1
  d = $2 + 0.0
  ds = abs(($3 + 0.0) - ($4 + 0.0))
  dr = abs(($5 + 0.0) - ($6 + 0.0))
  dc = abs(($7 + 0.0) - ($8 + 0.0))
  drw = abs(($9 + 0.0) - ($10 + 0.0))
  dcw = abs(($11 + 0.0) - ($12 + 0.0))
  ddw = abs(($13 + 0.0) - ($14 + 0.0))
  count[p]++
  sumDiff[p] += d
  if (count[p] == 1 || d > maxDiff[p]) maxDiff[p] = d
  if (count[p] == 1 || ds > maxShimmer[p]) maxShimmer[p] = ds
  if (count[p] == 1 || dr > maxReject[p]) maxReject[p] = dr
  if (count[p] == 1 || dc > maxConf[p]) maxConf[p] = dc
  if (count[p] == 1 || drw > maxRejectWindow[p]) maxRejectWindow[p] = drw
  if (count[p] == 1 || dcw > maxConfWindow[p]) maxConfWindow[p] = dcw
  if (count[p] == 1 || ddw > maxDropWindow[p]) maxDropWindow[p] = ddw
}
END {
  print "#profile\truns\tavgDiff\tmaxDiff\trecommendedStrict\temitThreshold\tmaxShimmerDrift\tmaxRejectDrift\tmaxConfidenceDrift\tmaxRejectWindowDrift\tmaxConfidenceWindowDrift\tmaxDropWindowDrift"
  for (p in count) {
    avg = sumDiff[p] / count[p]
    rec = maxDiff[p] * 1.06 + 0.002
    if (rec > 1.0) rec = 1.0
    emit = count[p] >= min_runs ? "yes" : "no"
    printf "%s\t%d\t%.6f\t%.6f\t%.6f\t%s\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\n", p, count[p], avg, maxDiff[p], rec, emit, maxShimmer[p], maxReject[p], maxConf[p], maxRejectWindow[p], maxConfWindow[p], maxDropWindow[p]
  }
}
' "$TMP_INPUT" | sort > "$REPORT_TSV"

{
  echo "# Generated by scripts/aa_lock_thresholds.sh"
  echo "# Source: $SOURCE_DIR"
  echo "# Minimum runs per profile: $MIN_RUNS"
  echo "# Real Vulkan threshold recommendations"
  awk -F'\t' 'NR > 1 && $6 == "yes" { gsub(/[^a-zA-Z0-9._-]/, "_", $1); printf "threshold.%s=%.6f\n", $1, $5 }' "$REPORT_TSV"
} > "$RECOMMENDED_PROPS"

echo "AA threshold lock report: $REPORT_TSV"
echo "AA threshold recommendations: $RECOMMENDED_PROPS"
