#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

SOURCE_DIR="${1:-artifacts/compare}"
OUT_DIR="${2:-artifacts/compare/threshold-lock}"
mkdir -p "$OUT_DIR"

TMP_INPUT="$(mktemp -t dle-aa-lock-input.XXXXXX.tsv)"
trap 'rm -f "$TMP_INPUT"' EXIT

while IFS= read -r meta; do
  mode="$(sed -n 's/^compare\.vulkan\.mode=//p' "$meta" | tail -n1)"
  profile="$(sed -n 's/^compare\.profileTag=//p' "$meta" | tail -n1)"
  diff="$(sed -n 's/^compare\.diffMetric=//p' "$meta" | tail -n1)"
  og_shimmer="$(sed -n 's/^compare\.opengl\.shimmerIndex=//p' "$meta" | tail -n1)"
  vk_shimmer="$(sed -n 's/^compare\.vulkan\.shimmerIndex=//p' "$meta" | tail -n1)"
  og_reject="$(sed -n 's/^compare\.opengl\.taaHistoryRejectRate=//p' "$meta" | tail -n1)"
  vk_reject="$(sed -n 's/^compare\.vulkan\.taaHistoryRejectRate=//p' "$meta" | tail -n1)"
  og_conf="$(sed -n 's/^compare\.opengl\.taaConfidenceMean=//p' "$meta" | tail -n1)"
  vk_conf="$(sed -n 's/^compare\.vulkan\.taaConfidenceMean=//p' "$meta" | tail -n1)"
  if [[ -z "$mode" || -z "$profile" || -z "$diff" ]]; then
    continue
  fi
  if [[ "$mode" != "vulkan_real" ]]; then
    continue
  fi
  echo -e "${profile}\t${diff}\t${og_shimmer:-0}\t${vk_shimmer:-0}\t${og_reject:-0}\t${vk_reject:-0}\t${og_conf:-0}\t${vk_conf:-0}" >> "$TMP_INPUT"
done < <(find "$SOURCE_DIR" -type f -name 'compare-metadata.properties' 2>/dev/null | sort)

if [[ ! -s "$TMP_INPUT" ]]; then
  echo "No real Vulkan compare metadata found under: $SOURCE_DIR" >&2
  exit 1
fi

REPORT_TSV="$OUT_DIR/threshold-lock-report.tsv"
RECOMMENDED_PROPS="$OUT_DIR/recommended-thresholds.properties"

awk -F'\t' '
function abs(x) { return x < 0 ? -x : x }
{
  p = $1
  d = $2 + 0.0
  ds = abs(($3 + 0.0) - ($4 + 0.0))
  dr = abs(($5 + 0.0) - ($6 + 0.0))
  dc = abs(($7 + 0.0) - ($8 + 0.0))
  count[p]++
  sumDiff[p] += d
  if (count[p] == 1 || d > maxDiff[p]) maxDiff[p] = d
  if (count[p] == 1 || ds > maxShimmer[p]) maxShimmer[p] = ds
  if (count[p] == 1 || dr > maxReject[p]) maxReject[p] = dr
  if (count[p] == 1 || dc > maxConf[p]) maxConf[p] = dc
}
END {
  print "#profile\truns\tavgDiff\tmaxDiff\trecommendedStrict\tmaxShimmerDrift\tmaxRejectDrift\tmaxConfidenceDrift"
  for (p in count) {
    avg = sumDiff[p] / count[p]
    rec = maxDiff[p] * 1.08 + 0.003
    if (rec > 1.0) rec = 1.0
    printf "%s\t%d\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\n", p, count[p], avg, maxDiff[p], rec, maxShimmer[p], maxReject[p], maxConf[p]
  }
}
' "$TMP_INPUT" | sort > "$REPORT_TSV"

{
  echo "# Generated by scripts/aa_lock_thresholds.sh"
  echo "# Source: $SOURCE_DIR"
  echo "# Real Vulkan threshold recommendations"
  awk -F'\t' 'NR > 1 { gsub(/[^a-zA-Z0-9._-]/, "_", $1); printf "threshold.%s=%.6f\n", $1, $5 }' "$REPORT_TSV"
} > "$RECOMMENDED_PROPS"

echo "AA threshold lock report: $REPORT_TSV"
echo "AA threshold recommendations: $RECOMMENDED_PROPS"
