#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

source "$ROOT_DIR/scripts/check_java25.sh"
enforce_java25_for_maven

OUT_ROOT="${DLE_AA_STABLE_PROMOTE_OUTPUT_ROOT:-artifacts/compare/aa-stable-promote-$(date +%Y%m%d-%H%M%S)}"
RUNS_PER_PASS="${DLE_AA_STABLE_PROMOTE_RUNS_PER_PASS:-3}"
MIN_RUNS="${DLE_AA_STABLE_PROMOTE_MIN_RUNS:-$RUNS_PER_PASS}"
PROMOTE_MODE="${DLE_AA_STABLE_PROMOTE_MODE:-real}" # real|mock
JVM_STACK_SIZE="${DLE_AA_STABLE_PROMOTE_JVM_STACK_SIZE:-${DLE_COMPARE_JVM_STACK_SIZE:-12m}}"
DIFF_MODE="${DLE_AA_STABLE_PROMOTE_DIFF_MODE:-conservative}" # strict|conservative
MERGE_MARGIN="${DLE_AA_STABLE_PROMOTE_MERGE_MARGIN:-0.0015}"
STRICT_VARIANCE_CAPS_FILE="${DLE_AA_STABLE_PROMOTE_VARIANCE_CAPS_FILE:-$ROOT_DIR/scripts/aa_variance_caps.properties}"
STRICT_ACCEPTED_MERGE_MARGIN="${DLE_AA_STRICT_ACCEPTED_MERGE_MARGIN:-0.0005}"

PASS1="$OUT_ROOT/pass-1"
PASS2="$OUT_ROOT/pass-2"
REC1="$PASS1/threshold-lock/recommended-thresholds.properties"
REC2="$PASS2/threshold-lock/recommended-thresholds.properties"

echo "AA stable threshold promotion (real Vulkan)"
echo "  output root: $OUT_ROOT"
echo "  runs/pass: $RUNS_PER_PASS"
echo "  min runs: $MIN_RUNS"
echo "  promote mode: $PROMOTE_MODE"
echo "  jvm stack size: $JVM_STACK_SIZE"
echo "  diff mode: $DIFF_MODE"
if [[ "$DIFF_MODE" == "strict" ]]; then
  echo "  strict caps: $STRICT_VARIANCE_CAPS_FILE"
fi

declare -A _strict_cap_exact
declare -A _strict_cap_prefix
_strict_cap_default="0.0050"
_strict_caps_loaded=0

load_strict_caps() {
  if [[ $_strict_caps_loaded -eq 1 ]]; then
    return 0
  fi
  _strict_caps_loaded=1
  if [[ ! -f "$STRICT_VARIANCE_CAPS_FILE" ]]; then
    return 0
  fi
  while IFS='=' read -r raw_key raw_value; do
    key="$(echo "${raw_key}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    value="$(echo "${raw_value:-}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [[ -z "$key" || "${key:0:1}" == "#" ]] && continue
    if [[ "$key" == "cap.default" ]]; then
      _strict_cap_default="$value"
      continue
    fi
    if [[ "$key" == cap.prefix.* ]]; then
      prefix="${key#cap.prefix.}"
      _strict_cap_prefix["$prefix"]="$value"
      continue
    fi
    if [[ "$key" == cap.* ]]; then
      exact="${key#cap.}"
      _strict_cap_exact["$exact"]="$value"
    fi
  done < "$STRICT_VARIANCE_CAPS_FILE"
}

strict_cap_for_key() {
  local key="$1"
  if [[ -n "${_strict_cap_exact[$key]+x}" ]]; then
    echo "${_strict_cap_exact[$key]}"
    return 0
  fi
  local best=""
  for p in "${!_strict_cap_prefix[@]}"; do
    if [[ "$key" == "$p"* ]]; then
      if [[ ${#p} -gt ${#best} ]]; then
        best="$p"
      fi
    fi
  done
  if [[ -n "$best" ]]; then
    echo "${_strict_cap_prefix[$best]}"
    return 0
  fi
  echo "$_strict_cap_default"
}

promote_conservative_merge() {
  local rec_a="$1"
  local rec_b="$2"
  local merged_out="$3"
  local margin="$4"
  awk -F= -v margin="$margin" '
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    NF < 2 { next }
    {
      key = $1
      val = $2 + 0.0
      if (!(key in maxv) || val > maxv[key]) {
        maxv[key] = val
      }
    }
    END {
      print "# Generated by scripts/aa_threshold_promote_stable_real.sh"
      print "# Rule: max(pass1, pass2) + margin"
      for (k in maxv) {
        out = maxv[k] + margin
        if (out > 1.0) out = 1.0
        printf "%s=%.6f\n", k, out
      }
    }
  ' "$rec_a" "$rec_b" | sort > "$merged_out"
}

run_pass() {
  local pass_out="$1"
  DLE_COMPARE_LONGRUN_OUTPUT_ROOT="$pass_out" \
  DLE_COMPARE_LONGRUN_RUNS="$RUNS_PER_PASS" \
  DLE_COMPARE_THRESHOLD_LOCK_MIN_RUNS="$MIN_RUNS" \
  DLE_COMPARE_JVM_STACK_SIZE="$JVM_STACK_SIZE" \
  DLE_COMPARE_VULKAN_MODE=real \
  "$ROOT_DIR/scripts/aa_longrun_real_sampling_mac.sh"
}

run_pass "$PASS1"
run_pass "$PASS2"

if [[ ! -f "$REC1" || ! -f "$REC2" ]]; then
  echo "Missing recommendation files:" >&2
  echo "  $REC1" >&2
  echo "  $REC2" >&2
  exit 1
fi

if cmp -s "$REC1" "$REC2"; then
  echo "Stable recommendation detected across both passes; promoting to $PROMOTE_MODE profile."
  "$ROOT_DIR/scripts/promote_compare_thresholds.sh" "$REC2" "$PROMOTE_MODE"
  echo "Promotion complete."
else
  if [[ "$DIFF_MODE" == "strict" ]]; then
    load_strict_caps
    declare -A pass1_vals
    declare -A pass2_vals
    declare -A all_keys
    while IFS='=' read -r key value; do
      [[ -z "$key" || "${key:0:1}" == "#" ]] && continue
      pass1_vals["$key"]="$value"
      all_keys["$key"]=1
    done < "$REC1"
    while IFS='=' read -r key value; do
      [[ -z "$key" || "${key:0:1}" == "#" ]] && continue
      pass2_vals["$key"]="$value"
      all_keys["$key"]=1
    done < "$REC2"

    STRICT_VARIANCE_REPORT="$OUT_ROOT/strict-variance-report.tsv"
    {
      echo -e "#key\tdelta\tcap\tpass1\tpass2\tstatus"
      unstable_count=0
      for key in "${!all_keys[@]}"; do
        a="${pass1_vals[$key]:-0}"
        b="${pass2_vals[$key]:-0}"
        delta="$(awk -v x="$a" -v y="$b" 'BEGIN { d=x-y; if (d < 0) d=-d; printf "%.6f", d }')"
        cap="$(strict_cap_for_key "$key")"
        status="ok"
        if ! awk -v d="$delta" -v c="$cap" 'BEGIN { exit !(d <= c) }'; then
          status="unstable"
          unstable_count=$((unstable_count + 1))
        fi
        echo -e "${key}\t${delta}\t${cap}\t${a}\t${b}\t${status}"
      done | sort
      echo "__UNSTABLE_COUNT__=$unstable_count"
    } > "$STRICT_VARIANCE_REPORT"

    unstable_count="$(awk -F= '/^__UNSTABLE_COUNT__=/{print $2}' "$STRICT_VARIANCE_REPORT")"
    sed -i '' '/^__UNSTABLE_COUNT__=/d' "$STRICT_VARIANCE_REPORT"
    echo "Strict variance report: $STRICT_VARIANCE_REPORT"

    if [[ "${unstable_count:-0}" -gt 0 ]]; then
      echo "Recommendations differ with material drift; skipping strict promotion." >&2
      echo "Unstable profiles: $unstable_count" >&2
      echo "Top unstable deltas:" >&2
      awk -F'\t' 'NR>1 && $6=="unstable"{print $0}' "$STRICT_VARIANCE_REPORT" | sort -t$'\t' -k2,2nr | head -n 20 >&2 || true
      exit 2
    fi

    MERGED_STRICT="$OUT_ROOT/recommended-thresholds-strict-variance-accepted.properties"
    promote_conservative_merge "$REC1" "$REC2" "$MERGED_STRICT" "$STRICT_ACCEPTED_MERGE_MARGIN"
    echo "Strict variance caps passed; promoting merged strict thresholds: $MERGED_STRICT"
    "$ROOT_DIR/scripts/promote_compare_thresholds.sh" "$MERGED_STRICT" "$PROMOTE_MODE"
    echo "Promotion complete (strict mode with variance caps)."
    exit 0
  fi
  if [[ "$DIFF_MODE" != "conservative" ]]; then
    echo "Invalid DLE_AA_STABLE_PROMOTE_DIFF_MODE='$DIFF_MODE' (expected strict|conservative)." >&2
    exit 2
  fi
  MERGED="$OUT_ROOT/recommended-thresholds-conservative.properties"
  echo "Recommendations differ; generating conservative merged thresholds."
  promote_conservative_merge "$REC1" "$REC2" "$MERGED" "$MERGE_MARGIN"
  echo "Conservative merged thresholds: $MERGED"
  "$ROOT_DIR/scripts/promote_compare_thresholds.sh" "$MERGED" "$PROMOTE_MODE"
  echo "Promotion complete (conservative mode)."
fi
