package org.dynamislight.impl.vulkan.uniform;

public final class VulkanGlobalSceneUniformCoordinator {
    private VulkanGlobalSceneUniformCoordinator() {
    }

    public static VulkanUniformWriters.GlobalSceneUniformInput build(BuildRequest in) {
        return VulkanGlobalSceneInputBuilder.build(
                new VulkanGlobalSceneInputBuilder.Inputs(
                        in.globalSceneUniformBytes(),
                        in.viewMatrix(),
                        in.projMatrix(),
                        in.dirLightDirX(),
                        in.dirLightDirY(),
                        in.dirLightDirZ(),
                        in.dirLightColorR(),
                        in.dirLightColorG(),
                        in.dirLightColorB(),
                        in.pointLightPosX(),
                        in.pointLightPosY(),
                        in.pointLightPosZ(),
                        in.pointShadowFarPlane(),
                        in.pointLightColorR(),
                        in.pointLightColorG(),
                        in.pointLightColorB(),
                        in.pointLightDirX(),
                        in.pointLightDirY(),
                        in.pointLightDirZ(),
                        in.pointLightInnerCos(),
                        in.pointLightOuterCos(),
                        in.pointLightIsSpot(),
                        in.pointShadowEnabled(),
                        in.localLightCount(),
                        in.maxLocalLights(),
                        in.localLightPosRange(),
                        in.localLightColorIntensity(),
                        in.localLightDirInner(),
                        in.localLightOuterTypeShadow(),
                        in.shadowFilterMode(),
                        in.shadowContactShadows(),
                        in.dirLightIntensity(),
                        in.pointLightIntensity(),
                        in.shadowEnabled(),
                        in.shadowStrength(),
                        in.shadowBias(),
                        in.shadowNormalBiasScale(),
                        in.shadowSlopeBiasScale(),
                        in.shadowPcfRadius(),
                        in.shadowCascadeCount(),
                        in.shadowMapResolution(),
                        in.shadowCascadeSplitNdc(),
                        in.fogEnabled(),
                        in.fogDensity(),
                        in.fogR(),
                        in.fogG(),
                        in.fogB(),
                        in.fogSteps(),
                        in.smokeEnabled(),
                        in.smokeIntensity(),
                        in.swapchainWidth(),
                        in.swapchainHeight(),
                        in.smokeR(),
                        in.smokeG(),
                        in.smokeB(),
                        in.iblEnabled(),
                        in.iblDiffuseStrength(),
                        in.iblSpecularStrength(),
                        in.iblPrefilterStrength(),
                        in.postOffscreenActive(),
                        in.tonemapEnabled(),
                        in.tonemapExposure(),
                        in.tonemapGamma(),
                        in.bloomEnabled(),
                        in.bloomThreshold(),
                        in.bloomStrength(),
                        in.ssaoEnabled(),
                        in.ssaoStrength(),
                        in.ssaoRadius(),
                        in.ssaoBias(),
                        in.ssaoPower(),
                        in.smaaEnabled(),
                        in.smaaStrength(),
                        in.prevViewProjMatrix(),
                        in.shadowLightViewProjMatrices()
                )
        );
    }

    public record BuildRequest(
            int globalSceneUniformBytes,
            float[] viewMatrix,
            float[] projMatrix,
            float dirLightDirX,
            float dirLightDirY,
            float dirLightDirZ,
            float dirLightColorR,
            float dirLightColorG,
            float dirLightColorB,
            float pointLightPosX,
            float pointLightPosY,
            float pointLightPosZ,
            float pointShadowFarPlane,
            float pointLightColorR,
            float pointLightColorG,
            float pointLightColorB,
            float pointLightDirX,
            float pointLightDirY,
            float pointLightDirZ,
            float pointLightInnerCos,
            float pointLightOuterCos,
            float pointLightIsSpot,
            boolean pointShadowEnabled,
            int localLightCount,
            int maxLocalLights,
            float[] localLightPosRange,
            float[] localLightColorIntensity,
            float[] localLightDirInner,
            float[] localLightOuterTypeShadow,
            int shadowFilterMode,
            boolean shadowContactShadows,
            float dirLightIntensity,
            float pointLightIntensity,
            boolean shadowEnabled,
            float shadowStrength,
            float shadowBias,
            float shadowNormalBiasScale,
            float shadowSlopeBiasScale,
            int shadowPcfRadius,
            int shadowCascadeCount,
            int shadowMapResolution,
            float[] shadowCascadeSplitNdc,
            boolean fogEnabled,
            float fogDensity,
            float fogR,
            float fogG,
            float fogB,
            int fogSteps,
            boolean smokeEnabled,
            float smokeIntensity,
            int swapchainWidth,
            int swapchainHeight,
            float smokeR,
            float smokeG,
            float smokeB,
            boolean iblEnabled,
            float iblDiffuseStrength,
            float iblSpecularStrength,
            float iblPrefilterStrength,
            boolean postOffscreenActive,
            boolean tonemapEnabled,
            float tonemapExposure,
            float tonemapGamma,
            boolean bloomEnabled,
            float bloomThreshold,
            float bloomStrength,
            boolean ssaoEnabled,
            float ssaoStrength,
            float ssaoRadius,
            float ssaoBias,
            float ssaoPower,
            boolean smaaEnabled,
            float smaaStrength,
            float[] prevViewProjMatrix,
            float[][] shadowLightViewProjMatrices
    ) {
    }
}
