package org.dynamislight.impl.vulkan.uniform;

public final class VulkanGlobalSceneInputBuilder {
    private VulkanGlobalSceneInputBuilder() {
    }

    public static VulkanUniformWriters.GlobalSceneUniformInput build(Inputs in) {
        return new VulkanUniformWriters.GlobalSceneUniformInput(
                in.globalSceneUniformBytes(),
                in.viewMatrix(),
                in.projMatrix(),
                in.dirLightDirX(),
                in.dirLightDirY(),
                in.dirLightDirZ(),
                in.shadowPcssSoftness(),
                in.dirLightColorR(),
                in.dirLightColorG(),
                in.dirLightColorB(),
                in.shadowMomentBlend(),
                in.pointLightPosX(),
                in.pointLightPosY(),
                in.pointLightPosZ(),
                in.pointShadowFarPlane(),
                in.pointLightColorR(),
                in.pointLightColorG(),
                in.pointLightColorB(),
                in.shadowMomentBleedReduction(),
                in.pointLightDirX(),
                in.pointLightDirY(),
                in.pointLightDirZ(),
                in.shadowContactStrength(),
                in.pointLightInnerCos(),
                in.pointLightOuterCos(),
                in.pointLightIsSpot(),
                in.pointShadowEnabled(),
                in.localLightCount(),
                in.maxLocalLights(),
                in.localLightPosRange(),
                in.localLightColorIntensity(),
                in.localLightDirInner(),
                in.localLightOuterTypeShadow(),
                in.shadowFilterMode(),
                in.shadowRtMode(),
                in.shadowRtActive(),
                in.shadowRtDenoiseStrength(),
                in.shadowRtRayLength(),
                in.shadowRtSampleCount(),
                in.shadowContactShadows(),
                in.dirLightIntensity(),
                in.pointLightIntensity(),
                in.shadowContactTemporalMotionScale(),
                in.shadowContactTemporalMinStability(),
                in.shadowEnabled(),
                in.shadowStrength(),
                in.shadowBias(),
                in.shadowNormalBiasScale(),
                in.shadowSlopeBiasScale(),
                in.shadowPcfRadius(),
                in.shadowCascadeCount(),
                in.shadowMapResolution(),
                in.shadowCascadeSplitNdc(),
                in.fogEnabled(),
                in.fogDensity(),
                in.fogR(),
                in.fogG(),
                in.fogB(),
                in.fogSteps(),
                in.smokeEnabled(),
                in.smokeIntensity(),
                in.swapchainWidth(),
                in.swapchainHeight(),
                in.smokeR(),
                in.smokeG(),
                in.smokeB(),
                in.iblEnabled(),
                in.iblDiffuseStrength(),
                in.iblSpecularStrength(),
                in.iblPrefilterStrength(),
                in.postOffscreenActive(),
                in.tonemapEnabled(),
                in.tonemapExposure(),
                in.tonemapGamma(),
                in.bloomEnabled(),
                in.bloomThreshold(),
                in.bloomStrength(),
                in.ssaoEnabled(),
                in.ssaoStrength(),
                in.ssaoRadius(),
                in.ssaoBias(),
                in.ssaoPower(),
                in.smaaEnabled(),
                in.smaaStrength(),
                in.prevViewProjMatrix(),
                in.shadowLightViewProjMatrices()
        );
    }

    public static VulkanUniformWriters.GlobalSceneUniformInput build(
            int globalSceneUniformBytes,
            float[] viewMatrix,
            float[] projMatrix,
            LightingInputs lighting,
            ShadowInputs shadow,
            AtmosphereInputs atmosphere,
            PostInputs post,
            float[][] shadowLightViewProjMatrices
    ) {
        return new VulkanUniformWriters.GlobalSceneUniformInput(
                globalSceneUniformBytes,
                viewMatrix,
                projMatrix,
                lighting.dirLightDirX(),
                lighting.dirLightDirY(),
                lighting.dirLightDirZ(),
                shadow.shadowPcssSoftness(),
                lighting.dirLightColorR(),
                lighting.dirLightColorG(),
                lighting.dirLightColorB(),
                shadow.shadowMomentBlend(),
                lighting.pointLightPosX(),
                lighting.pointLightPosY(),
                lighting.pointLightPosZ(),
                lighting.pointShadowFarPlane(),
                lighting.pointLightColorR(),
                lighting.pointLightColorG(),
                lighting.pointLightColorB(),
                shadow.shadowMomentBleedReduction(),
                lighting.pointLightDirX(),
                lighting.pointLightDirY(),
                lighting.pointLightDirZ(),
                shadow.shadowContactStrength(),
                lighting.pointLightInnerCos(),
                lighting.pointLightOuterCos(),
                lighting.pointLightIsSpot(),
                lighting.pointShadowEnabled(),
                lighting.localLightCount(),
                lighting.maxLocalLights(),
                lighting.localLightPosRange(),
                lighting.localLightColorIntensity(),
                lighting.localLightDirInner(),
                lighting.localLightOuterTypeShadow(),
                shadow.shadowFilterMode(),
                shadow.shadowRtMode(),
                shadow.shadowRtActive(),
                shadow.shadowRtDenoiseStrength(),
                shadow.shadowRtRayLength(),
                shadow.shadowRtSampleCount(),
                shadow.shadowContactShadows(),
                lighting.dirLightIntensity(),
                lighting.pointLightIntensity(),
                shadow.shadowContactTemporalMotionScale(),
                shadow.shadowContactTemporalMinStability(),
                shadow.shadowEnabled(),
                shadow.shadowStrength(),
                shadow.shadowBias(),
                shadow.shadowNormalBiasScale(),
                shadow.shadowSlopeBiasScale(),
                shadow.shadowPcfRadius(),
                shadow.shadowCascadeCount(),
                shadow.shadowMapResolution(),
                shadow.shadowCascadeSplitNdc(),
                atmosphere.fogEnabled(),
                atmosphere.fogDensity(),
                atmosphere.fogR(),
                atmosphere.fogG(),
                atmosphere.fogB(),
                atmosphere.fogSteps(),
                atmosphere.smokeEnabled(),
                atmosphere.smokeIntensity(),
                atmosphere.swapchainWidth(),
                atmosphere.swapchainHeight(),
                atmosphere.smokeR(),
                atmosphere.smokeG(),
                atmosphere.smokeB(),
                atmosphere.iblEnabled(),
                atmosphere.iblDiffuseStrength(),
                atmosphere.iblSpecularStrength(),
                atmosphere.iblPrefilterStrength(),
                post.postOffscreenActive(),
                post.tonemapEnabled(),
                post.tonemapExposure(),
                post.tonemapGamma(),
                post.bloomEnabled(),
                post.bloomThreshold(),
                post.bloomStrength(),
                post.ssaoEnabled(),
                post.ssaoStrength(),
                post.ssaoRadius(),
                post.ssaoBias(),
                post.ssaoPower(),
                post.smaaEnabled(),
                post.smaaStrength(),
                post.prevViewProjMatrix(),
                shadowLightViewProjMatrices
        );
    }

    public record Inputs(
            int globalSceneUniformBytes,
            float[] viewMatrix,
            float[] projMatrix,
            float dirLightDirX,
            float dirLightDirY,
            float dirLightDirZ,
            float shadowPcssSoftness,
            float dirLightColorR,
            float dirLightColorG,
            float dirLightColorB,
            float shadowMomentBlend,
            float pointLightPosX,
            float pointLightPosY,
            float pointLightPosZ,
            float pointShadowFarPlane,
            float pointLightColorR,
            float pointLightColorG,
            float pointLightColorB,
            float shadowMomentBleedReduction,
            float pointLightDirX,
            float pointLightDirY,
            float pointLightDirZ,
            float shadowContactStrength,
            float pointLightInnerCos,
            float pointLightOuterCos,
            float pointLightIsSpot,
            boolean pointShadowEnabled,
            int localLightCount,
            int maxLocalLights,
            float[] localLightPosRange,
            float[] localLightColorIntensity,
            float[] localLightDirInner,
            float[] localLightOuterTypeShadow,
            int shadowFilterMode,
            int shadowRtMode,
            boolean shadowRtActive,
            float shadowRtDenoiseStrength,
            float shadowRtRayLength,
            int shadowRtSampleCount,
            boolean shadowContactShadows,
            float dirLightIntensity,
            float pointLightIntensity,
            float shadowContactTemporalMotionScale,
            float shadowContactTemporalMinStability,
            boolean shadowEnabled,
            float shadowStrength,
            float shadowBias,
            float shadowNormalBiasScale,
            float shadowSlopeBiasScale,
            int shadowPcfRadius,
            int shadowCascadeCount,
            int shadowMapResolution,
            float[] shadowCascadeSplitNdc,
            boolean fogEnabled,
            float fogDensity,
            float fogR,
            float fogG,
            float fogB,
            int fogSteps,
            boolean smokeEnabled,
            float smokeIntensity,
            int swapchainWidth,
            int swapchainHeight,
            float smokeR,
            float smokeG,
            float smokeB,
            boolean iblEnabled,
            float iblDiffuseStrength,
            float iblSpecularStrength,
            float iblPrefilterStrength,
            boolean postOffscreenActive,
            boolean tonemapEnabled,
            float tonemapExposure,
            float tonemapGamma,
            boolean bloomEnabled,
            float bloomThreshold,
            float bloomStrength,
            boolean ssaoEnabled,
            float ssaoStrength,
            float ssaoRadius,
            float ssaoBias,
            float ssaoPower,
            boolean smaaEnabled,
            float smaaStrength,
            float[] prevViewProjMatrix,
            float[][] shadowLightViewProjMatrices
    ) {
    }

    public record LightingInputs(
            float dirLightDirX,
            float dirLightDirY,
            float dirLightDirZ,
            float dirLightColorR,
            float dirLightColorG,
            float dirLightColorB,
            float pointLightPosX,
            float pointLightPosY,
            float pointLightPosZ,
            float pointShadowFarPlane,
            float pointLightColorR,
            float pointLightColorG,
            float pointLightColorB,
            float pointLightDirX,
            float pointLightDirY,
            float pointLightDirZ,
            float pointLightInnerCos,
            float pointLightOuterCos,
            float pointLightIsSpot,
            boolean pointShadowEnabled,
            int localLightCount,
            int maxLocalLights,
            float[] localLightPosRange,
            float[] localLightColorIntensity,
            float[] localLightDirInner,
            float[] localLightOuterTypeShadow,
            float dirLightIntensity,
            float pointLightIntensity
    ) {
    }

    public record ShadowInputs(
            boolean shadowEnabled,
            float shadowStrength,
            float shadowBias,
            float shadowNormalBiasScale,
            float shadowSlopeBiasScale,
            int shadowPcfRadius,
            int shadowCascadeCount,
            int shadowMapResolution,
            float[] shadowCascadeSplitNdc,
            int shadowFilterMode,
            int shadowRtMode,
            boolean shadowRtActive,
            float shadowRtDenoiseStrength,
            float shadowRtRayLength,
            int shadowRtSampleCount,
            boolean shadowContactShadows,
            float shadowContactTemporalMotionScale,
            float shadowContactTemporalMinStability,
            float shadowPcssSoftness,
            float shadowMomentBlend,
            float shadowMomentBleedReduction,
            float shadowContactStrength
    ) {
    }

    public record AtmosphereInputs(
            boolean fogEnabled,
            float fogDensity,
            float fogR,
            float fogG,
            float fogB,
            int fogSteps,
            boolean smokeEnabled,
            float smokeIntensity,
            int swapchainWidth,
            int swapchainHeight,
            float smokeR,
            float smokeG,
            float smokeB,
            boolean iblEnabled,
            float iblDiffuseStrength,
            float iblSpecularStrength,
            float iblPrefilterStrength
    ) {
    }

    public record PostInputs(
            boolean postOffscreenActive,
            boolean tonemapEnabled,
            float tonemapExposure,
            float tonemapGamma,
            boolean bloomEnabled,
            float bloomThreshold,
            float bloomStrength,
            boolean ssaoEnabled,
            float ssaoStrength,
            float ssaoRadius,
            float ssaoBias,
            float ssaoPower,
            boolean smaaEnabled,
            float smaaStrength,
            float[] prevViewProjMatrix
    ) {
    }
}
