package org.dynamisengine.light.impl.vulkan.swapchain;

import org.dynamisengine.light.api.error.EngineException;
import org.dynamisengine.light.impl.vulkan.pipeline.VulkanPostProcessResources;
import org.lwjgl.system.MemoryStack;
import org.lwjgl.vulkan.VkDevice;
import org.lwjgl.vulkan.VkPhysicalDevice;

import static org.lwjgl.vulkan.VK10.VK_NULL_HANDLE;

public final class VulkanSwapchainLifecycleCoordinator {
    private VulkanSwapchainLifecycleCoordinator() {
    }

    public static State create(CreateRequest request) throws EngineException {
        VulkanSwapchainResourceCoordinator.Allocation allocation = VulkanSwapchainResourceCoordinator.create(
                new VulkanSwapchainResourceCoordinator.CreateInputs(
                        request.physicalDevice(),
                        request.device(),
                        request.stack(),
                        request.surface(),
                        request.requestedWidth(),
                        request.requestedHeight(),
                        request.depthFormat(),
                        request.vertexStrideBytes(),
                        request.descriptorSetLayout(),
                        request.textureDescriptorSetLayout(),
                        request.skinnedDescriptorSetLayout(),
                        request.bindlessDescriptorSetLayout(),
                        request.postOffscreenRequested(),
                        request.postDescriptorPlan(),
                        request.mainFragmentSource(),
                        request.postFragmentSource()
                )
        );
        VulkanPostProcessResources.Allocation postResources = allocation.postProcessResources();
        return new State(
                allocation.swapchain(),
                allocation.swapchainImageFormat(),
                allocation.swapchainWidth(),
                allocation.swapchainHeight(),
                allocation.swapchainImages(),
                allocation.swapchainImageViews(),
                allocation.depthImages(),
                allocation.depthMemories(),
                allocation.depthImageViews(),
                allocation.velocityImage(),
                allocation.velocityMemory(),
                allocation.velocityImageView(),
                allocation.renderPass(),
                allocation.pipelineLayout(),
                allocation.graphicsPipeline(),
                allocation.bindlessStaticPipelineLayout(),
                allocation.bindlessStaticGraphicsPipeline(),
                allocation.bindlessSkinnedPipelineLayout(),
                allocation.bindlessSkinnedGraphicsPipeline(),
                allocation.bindlessMorphPipelineLayout(),
                allocation.bindlessMorphGraphicsPipeline(),
                allocation.bindlessSkinnedMorphPipelineLayout(),
                allocation.bindlessSkinnedMorphGraphicsPipeline(),
                allocation.bindlessInstancedPipelineLayout(),
                allocation.bindlessInstancedGraphicsPipeline(),
                allocation.morphPipelineLayout(),
                allocation.morphGraphicsPipeline(),
                allocation.skinnedPipelineLayout(),
                allocation.skinnedGraphicsPipeline(),
                allocation.skinnedMorphPipelineLayout(),
                allocation.skinnedMorphGraphicsPipeline(),
                allocation.instancedPipelineLayout(),
                allocation.instancedGraphicsPipeline(),
                allocation.framebuffers(),
                allocation.postOffscreenActive(),
                postResources.offscreenColorImage(),
                postResources.offscreenColorMemory(),
                postResources.offscreenColorImageView(),
                postResources.offscreenColorSampler(),
                postResources.taaHistoryImage(),
                postResources.taaHistoryMemory(),
                postResources.taaHistoryImageView(),
                postResources.taaHistorySampler(),
                postResources.taaHistoryVelocityImage(),
                postResources.taaHistoryVelocityMemory(),
                postResources.taaHistoryVelocityImageView(),
                postResources.taaHistoryVelocitySampler(),
                postResources.planarCaptureImage(),
                postResources.planarCaptureMemory(),
                postResources.planarCaptureImageView(),
                postResources.planarCaptureSampler(),
                postResources.postDescriptorSetLayout(),
                postResources.postDescriptorPool(),
                postResources.postDescriptorSet(),
                postResources.postRenderPass(),
                postResources.postPipelineLayout(),
                postResources.postGraphicsPipeline(),
                postResources.postFramebuffers(),
                false,
                false
        );
    }

    public static State destroy(DestroyRequest request) {
        VulkanSwapchainDestroyCoordinator.Result result = VulkanSwapchainDestroyCoordinator.destroy(
                new VulkanSwapchainDestroyCoordinator.DestroyInputs(
                        request.device(),
                        request.framebuffers(),
                        request.graphicsPipeline(),
                        request.bindlessStaticGraphicsPipeline(),
                        request.bindlessSkinnedGraphicsPipeline(),
                        request.bindlessMorphGraphicsPipeline(),
                        request.bindlessSkinnedMorphGraphicsPipeline(),
                        request.bindlessInstancedGraphicsPipeline(),
                        request.morphGraphicsPipeline(),
                        request.skinnedGraphicsPipeline(),
                        request.skinnedMorphGraphicsPipeline(),
                        request.instancedGraphicsPipeline(),
                        request.pipelineLayout(),
                        request.bindlessStaticPipelineLayout(),
                        request.bindlessSkinnedPipelineLayout(),
                        request.bindlessMorphPipelineLayout(),
                        request.bindlessSkinnedMorphPipelineLayout(),
                        request.bindlessInstancedPipelineLayout(),
                        request.morphPipelineLayout(),
                        request.skinnedPipelineLayout(),
                        request.skinnedMorphPipelineLayout(),
                        request.instancedPipelineLayout(),
                        request.renderPass(),
                        request.swapchainImageViews(),
                        request.depthImages(),
                        request.depthMemories(),
                        request.depthImageViews(),
                        request.velocityImage(),
                        request.velocityMemory(),
                        request.velocityImageView(),
                        request.swapchain(),
                        new VulkanPostProcessResources.Allocation(
                                request.offscreenColorImage(),
                                request.offscreenColorMemory(),
                                request.offscreenColorImageView(),
                                request.offscreenColorSampler(),
                                request.postTaaHistoryImage(),
                                request.postTaaHistoryMemory(),
                                request.postTaaHistoryImageView(),
                                request.postTaaHistorySampler(),
                                request.postTaaHistoryVelocityImage(),
                                request.postTaaHistoryVelocityMemory(),
                                request.postTaaHistoryVelocityImageView(),
                                request.postTaaHistoryVelocitySampler(),
                                request.postPlanarCaptureImage(),
                                request.postPlanarCaptureMemory(),
                                request.postPlanarCaptureImageView(),
                                request.postPlanarCaptureSampler(),
                                request.postDescriptorSetLayout(),
                                request.postDescriptorPool(),
                                request.postDescriptorSet(),
                                request.postRenderPass(),
                                request.postPipelineLayout(),
                                request.postGraphicsPipeline(),
                                request.postFramebuffers()
                        )
                )
        );
        if (result == null) {
            return null;
        }
        return new State(
                result.swapchain(),
                request.swapchainImageFormat(),
                request.swapchainWidth(),
                request.swapchainHeight(),
                result.swapchainImages(),
                result.swapchainImageViews(),
                result.depthImages(),
                result.depthMemories(),
                result.depthImageViews(),
                result.velocityImage(),
                result.velocityMemory(),
                result.velocityImageView(),
                result.renderPass(),
                result.pipelineLayout(),
                result.graphicsPipeline(),
                result.bindlessStaticPipelineLayout(),
                result.bindlessStaticGraphicsPipeline(),
                result.bindlessSkinnedPipelineLayout(),
                result.bindlessSkinnedGraphicsPipeline(),
                result.bindlessMorphPipelineLayout(),
                result.bindlessMorphGraphicsPipeline(),
                result.bindlessSkinnedMorphPipelineLayout(),
                result.bindlessSkinnedMorphGraphicsPipeline(),
                result.bindlessInstancedPipelineLayout(),
                result.bindlessInstancedGraphicsPipeline(),
                result.morphPipelineLayout(),
                result.morphGraphicsPipeline(),
                result.skinnedPipelineLayout(),
                result.skinnedGraphicsPipeline(),
                result.skinnedMorphPipelineLayout(),
                result.skinnedMorphGraphicsPipeline(),
                result.instancedPipelineLayout(),
                result.instancedGraphicsPipeline(),
                result.framebuffers(),
                result.postOffscreenActive(),
                result.offscreenColorImage(),
                result.offscreenColorMemory(),
                result.offscreenColorImageView(),
                result.offscreenColorSampler(),
                result.postTaaHistoryImage(),
                result.postTaaHistoryMemory(),
                result.postTaaHistoryImageView(),
                result.postTaaHistorySampler(),
                result.postTaaHistoryVelocityImage(),
                result.postTaaHistoryVelocityMemory(),
                result.postTaaHistoryVelocityImageView(),
                result.postTaaHistoryVelocitySampler(),
                result.postPlanarCaptureImage(),
                result.postPlanarCaptureMemory(),
                result.postPlanarCaptureImageView(),
                result.postPlanarCaptureSampler(),
                result.postDescriptorSetLayout(),
                result.postDescriptorPool(),
                result.postDescriptorSet(),
                result.postRenderPass(),
                result.postPipelineLayout(),
                result.postGraphicsPipeline(),
                result.postFramebuffers(),
                result.postIntermediateInitialized(),
                result.postTaaHistoryInitialized()
        );
    }

    public record CreateRequest(
            VkPhysicalDevice physicalDevice,
            VkDevice device,
            MemoryStack stack,
            long surface,
            int requestedWidth,
            int requestedHeight,
            int depthFormat,
            int vertexStrideBytes,
            long descriptorSetLayout,
            long textureDescriptorSetLayout,
            long skinnedDescriptorSetLayout,
            long bindlessDescriptorSetLayout,
            boolean postOffscreenRequested,
            org.dynamisengine.light.impl.vulkan.descriptor.VulkanComposedDescriptorLayoutPlan postDescriptorPlan,
            String mainFragmentSource,
            String postFragmentSource
    ) {
    }

    public record DestroyRequest(
            VkDevice device,
            long[] framebuffers,
            long graphicsPipeline,
            long bindlessStaticGraphicsPipeline,
            long bindlessSkinnedGraphicsPipeline,
            long bindlessMorphGraphicsPipeline,
            long bindlessSkinnedMorphGraphicsPipeline,
            long bindlessInstancedGraphicsPipeline,
            long pipelineLayout,
            long bindlessStaticPipelineLayout,
            long bindlessSkinnedPipelineLayout,
            long bindlessMorphPipelineLayout,
            long bindlessSkinnedMorphPipelineLayout,
            long bindlessInstancedPipelineLayout,
            long morphGraphicsPipeline,
            long morphPipelineLayout,
            long skinnedGraphicsPipeline,
            long skinnedPipelineLayout,
            long skinnedMorphGraphicsPipeline,
            long skinnedMorphPipelineLayout,
            long instancedGraphicsPipeline,
            long instancedPipelineLayout,
            long renderPass,
            long[] swapchainImageViews,
            long[] depthImages,
            long[] depthMemories,
            long[] depthImageViews,
            long velocityImage,
            long velocityMemory,
            long velocityImageView,
            long swapchain,
            int swapchainImageFormat,
            int swapchainWidth,
            int swapchainHeight,
            long offscreenColorImage,
            long offscreenColorMemory,
            long offscreenColorImageView,
            long offscreenColorSampler,
            long postTaaHistoryImage,
            long postTaaHistoryMemory,
            long postTaaHistoryImageView,
            long postTaaHistorySampler,
            long postTaaHistoryVelocityImage,
            long postTaaHistoryVelocityMemory,
            long postTaaHistoryVelocityImageView,
            long postTaaHistoryVelocitySampler,
            long postPlanarCaptureImage,
            long postPlanarCaptureMemory,
            long postPlanarCaptureImageView,
            long postPlanarCaptureSampler,
            long postDescriptorSetLayout,
            long postDescriptorPool,
            long postDescriptorSet,
            long postRenderPass,
            long postPipelineLayout,
            long postGraphicsPipeline,
            long[] postFramebuffers
    ) {
    }

    public record State(
            long swapchain,
            int swapchainImageFormat,
            int swapchainWidth,
            int swapchainHeight,
            long[] swapchainImages,
            long[] swapchainImageViews,
            long[] depthImages,
            long[] depthMemories,
            long[] depthImageViews,
            long velocityImage,
            long velocityMemory,
            long velocityImageView,
            long renderPass,
            long pipelineLayout,
            long graphicsPipeline,
            long bindlessStaticPipelineLayout,
            long bindlessStaticGraphicsPipeline,
            long bindlessSkinnedPipelineLayout,
            long bindlessSkinnedGraphicsPipeline,
            long bindlessMorphPipelineLayout,
            long bindlessMorphGraphicsPipeline,
            long bindlessSkinnedMorphPipelineLayout,
            long bindlessSkinnedMorphGraphicsPipeline,
            long bindlessInstancedPipelineLayout,
            long bindlessInstancedGraphicsPipeline,
            long morphPipelineLayout,
            long morphGraphicsPipeline,
            long skinnedPipelineLayout,
            long skinnedGraphicsPipeline,
            long skinnedMorphPipelineLayout,
            long skinnedMorphGraphicsPipeline,
            long instancedPipelineLayout,
            long instancedGraphicsPipeline,
            long[] framebuffers,
            boolean postOffscreenActive,
            long offscreenColorImage,
            long offscreenColorMemory,
            long offscreenColorImageView,
            long offscreenColorSampler,
            long postTaaHistoryImage,
            long postTaaHistoryMemory,
            long postTaaHistoryImageView,
            long postTaaHistorySampler,
            long postTaaHistoryVelocityImage,
            long postTaaHistoryVelocityMemory,
            long postTaaHistoryVelocityImageView,
            long postTaaHistoryVelocitySampler,
            long postPlanarCaptureImage,
            long postPlanarCaptureMemory,
            long postPlanarCaptureImageView,
            long postPlanarCaptureSampler,
            long postDescriptorSetLayout,
            long postDescriptorPool,
            long postDescriptorSet,
            long postRenderPass,
            long postPipelineLayout,
            long postGraphicsPipeline,
            long[] postFramebuffers,
            boolean postIntermediateInitialized,
            boolean postTaaHistoryInitialized
    ) {
        public static State empty() {
            return new State(
                    VK_NULL_HANDLE,
                    0,
                    1,
                    1,
                    new long[0],
                    new long[0],
                    new long[0],
                    new long[0],
                    new long[0],
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    new long[0],
                    false,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    VK_NULL_HANDLE,
                    new long[0],
                    false,
                    false
            );
        }
    }
}
