package org.dynamislight.impl.vulkan;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.Map;
import org.junit.jupiter.api.Test;

class VulkanRuntimeOptionsTest {
    @Test
    void parseShadowSchedulerOverrides() {
        VulkanRuntimeOptions.Parsed parsed = VulkanRuntimeOptions.parse(
                Map.ofEntries(
                        Map.entry("vulkan.shadow.maxLocalShadowLayers", "12"),
                        Map.entry("vulkan.shadow.maxShadowFacesPerFrame", "6"),
                        Map.entry("vulkan.shadow.maxShadowedLocalLights", "7"),
                        Map.entry("vulkan.shadow.rtBvhStrict", "true"),
                        Map.entry("vulkan.shadow.rtDenoiseStrength", "0.8"),
                        Map.entry("vulkan.shadow.rtRayLength", "120"),
                        Map.entry("vulkan.shadow.rtSampleCount", "4"),
                        Map.entry("vulkan.shadow.rtDedicatedDenoiseStrength", "0.9"),
                        Map.entry("vulkan.shadow.rtDedicatedRayLength", "160"),
                        Map.entry("vulkan.shadow.rtDedicatedSampleCount", "8"),
                        Map.entry("vulkan.shadow.rtProductionDenoiseStrength", "0.93"),
                        Map.entry("vulkan.shadow.rtProductionRayLength", "220"),
                        Map.entry("vulkan.shadow.rtProductionSampleCount", "12"),
                        Map.entry("vulkan.shadow.pcssSoftness", "1.4"),
                        Map.entry("vulkan.shadow.momentBlend", "0.9"),
                        Map.entry("vulkan.shadow.momentBleedReduction", "1.2"),
                        Map.entry("vulkan.shadow.contactStrength", "1.5"),
                        Map.entry("vulkan.shadow.contactTemporalMotionScale", "1.8"),
                        Map.entry("vulkan.shadow.contactTemporalMinStability", "0.55"),
                        Map.entry("vulkan.shadow.scheduler.enabled", "false"),
                        Map.entry("vulkan.shadow.scheduler.heroPeriod", "2"),
                        Map.entry("vulkan.shadow.scheduler.midPeriod", "3"),
                        Map.entry("vulkan.shadow.scheduler.distantPeriod", "8"),
                        Map.entry("vulkan.shadow.directionalTexelSnapEnabled", "false"),
                        Map.entry("vulkan.shadow.directionalTexelSnapScale", "1.75"),
                        Map.entry("vulkan.reflections.probeChurnWarnMinDelta", "2"),
                        Map.entry("vulkan.reflections.probeChurnWarnMinStreak", "5"),
                        Map.entry("vulkan.reflections.probeChurnWarnCooldownFrames", "240"),
                        Map.entry("vulkan.reflections.probeQualityOverlapWarnMaxPairs", "12"),
                        Map.entry("vulkan.reflections.probeQualityBleedRiskWarnMaxPairs", "2"),
                        Map.entry("vulkan.reflections.probeQualityMinOverlapPairsWhenMultiple", "3"),
                        Map.entry("vulkan.reflections.probeQualityBoxProjectionMinRatio", "0.82"),
                        Map.entry("vulkan.reflections.probeQualityInvalidBlendDistanceWarnMax", "4"),
                        Map.entry("vulkan.reflections.probeQualityOverlapCoverageWarnMin", "0.27"),
                        Map.entry("vulkan.reflections.ssrTaaInstabilityRejectMin", "0.42"),
                        Map.entry("vulkan.reflections.ssrTaaInstabilityConfidenceMax", "0.61"),
                        Map.entry("vulkan.reflections.ssrTaaInstabilityDropEventsMin", "3"),
                        Map.entry("vulkan.reflections.ssrTaaInstabilityWarnMinFrames", "6"),
                        Map.entry("vulkan.reflections.ssrTaaInstabilityWarnCooldownFrames", "180"),
                        Map.entry("vulkan.reflections.ssrTaaRiskEmaAlpha", "0.35"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveEnabled", "true"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTemporalBoostMax", "0.21"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveSsrStrengthScaleMin", "0.63"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveStepScaleBoostMax", "0.28"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendWindowFrames", "240"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendHighRatioWarnMin", "0.52"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendWarnMinFrames", "5"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendWarnCooldownFrames", "210"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendWarnMinSamples", "44"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendSloMeanSeverityMax", "0.36"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendSloHighRatioMax", "0.19"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendSloMinSamples", "28"),
                        Map.entry("vulkan.reflections.ssrTaaHistoryRejectSeverityMin", "0.81"),
                        Map.entry("vulkan.reflections.ssrTaaHistoryConfidenceDecaySeverityMin", "0.51"),
                        Map.entry("vulkan.reflections.ssrTaaHistoryRejectRiskStreakMin", "7"),
                        Map.entry("vulkan.reflections.ssrTaaDisocclusionRejectDropEventsMin", "6"),
                        Map.entry("vulkan.reflections.ssrTaaDisocclusionRejectConfidenceMax", "0.57"),
                        Map.entry("vulkan.reflections.ssrEnvelopeRejectWarnMax", "0.39"),
                        Map.entry("vulkan.reflections.ssrEnvelopeConfidenceWarnMin", "0.62"),
                        Map.entry("vulkan.reflections.ssrEnvelopeDropWarnMin", "5"),
                        Map.entry("vulkan.reflections.ssrEnvelopeWarnMinFrames", "4"),
                        Map.entry("vulkan.reflections.ssrEnvelopeWarnCooldownFrames", "180"),
                        Map.entry("vulkan.reflections.rtSingleBounceEnabled", "true"),
                        Map.entry("vulkan.reflections.rtMultiBounceEnabled", "true"),
                        Map.entry("vulkan.reflections.rtRequireActive", "true"),
                        Map.entry("vulkan.reflections.rtRequireMultiBounce", "true"),
                        Map.entry("vulkan.reflections.rtRequireDedicatedPipeline", "true"),
                        Map.entry("vulkan.reflections.rtDedicatedPipelineEnabled", "true"),
                        Map.entry("vulkan.reflections.rtDedicatedDenoisePipelineEnabled", "false"),
                        Map.entry("vulkan.reflections.rtDenoiseStrength", "0.73"),
                        Map.entry("vulkan.reflections.rtPerfMaxGpuMsLow", "1.3"),
                        Map.entry("vulkan.reflections.rtPerfMaxGpuMsMedium", "2.1"),
                        Map.entry("vulkan.reflections.rtPerfMaxGpuMsHigh", "2.9"),
                        Map.entry("vulkan.reflections.rtPerfMaxGpuMsUltra", "3.7"),
                        Map.entry("vulkan.reflections.rtPerfWarnMinFrames", "5"),
                        Map.entry("vulkan.reflections.rtPerfWarnCooldownFrames", "210"),
                        Map.entry("vulkan.reflections.rtHybridProbeShareWarnMax", "0.62"),
                        Map.entry("vulkan.reflections.rtHybridWarnMinFrames", "6"),
                        Map.entry("vulkan.reflections.rtHybridWarnCooldownFrames", "190"),
                        Map.entry("vulkan.reflections.rtDenoiseSpatialVarianceWarnMax", "0.33"),
                        Map.entry("vulkan.reflections.rtDenoiseTemporalLagWarnMax", "0.27"),
                        Map.entry("vulkan.reflections.rtDenoiseWarnMinFrames", "4"),
                        Map.entry("vulkan.reflections.rtDenoiseWarnCooldownFrames", "160"),
                        Map.entry("vulkan.reflections.rtAsBuildGpuMsWarnMax", "1.9"),
                        Map.entry("vulkan.reflections.rtAsMemoryBudgetMb", "88.0"),
                        Map.entry("vulkan.reflections.transparencyCandidateReactiveMin", "0.41"),
                        Map.entry("vulkan.reflections.transparencyProbeOnlyRatioWarnMax", "0.57"),
                        Map.entry("vulkan.reflections.transparencyWarnMinFrames", "5"),
                        Map.entry("vulkan.reflections.transparencyWarnCooldownFrames", "220"),
                        Map.entry("vulkan.reflections.planarPerfRequireGpuTimestamp", "true")
                        ,Map.entry("vulkan.reflections.probeUpdateCadenceFrames", "6")
                        ,Map.entry("vulkan.reflections.probeMaxVisible", "48")
                        ,Map.entry("vulkan.reflections.probeLodDepthScale", "1.8")
                        ,Map.entry("vulkan.reflections.probeStreamingWarnMinFrames", "7")
                        ,Map.entry("vulkan.reflections.probeStreamingWarnCooldownFrames", "222")
                        ,Map.entry("vulkan.reflections.probeStreamingMissRatioWarnMax", "0.24")
                        ,Map.entry("vulkan.reflections.probeStreamingDeferredRatioWarnMax", "0.41")
                        ,Map.entry("vulkan.reflections.probeStreamingLodSkewWarnMax", "0.66")
                        ,Map.entry("vulkan.reflections.probeStreamingMemoryBudgetMb", "96")
                ),
                256
        );

        assertEquals("off", VulkanRuntimeOptions.parse(Map.of("vulkan.shadow.rtMode", "invalid"), 256).shadowRtMode());
        assertEquals("bvh", VulkanRuntimeOptions.parse(Map.of("vulkan.shadow.rtMode", "bvh"), 256).shadowRtMode());
        assertEquals("bvh_dedicated", VulkanRuntimeOptions.parse(Map.of("vulkan.shadow.rtMode", "bvh_dedicated"), 256).shadowRtMode());
        assertEquals("bvh_production", VulkanRuntimeOptions.parse(Map.of("vulkan.shadow.rtMode", "bvh_production"), 256).shadowRtMode());
        assertEquals("rt_native", VulkanRuntimeOptions.parse(Map.of("vulkan.shadow.rtMode", "rt_native"), 256).shadowRtMode());
        assertEquals("rt_native_denoised", VulkanRuntimeOptions.parse(Map.of("vulkan.shadow.rtMode", "rt_native_denoised"), 256).shadowRtMode());
        assertEquals(true, parsed.shadowRtBvhStrict());
        assertEquals(7, parsed.shadowMaxShadowedLocalLights());
        assertEquals(12, parsed.shadowMaxLocalLayers());
        assertEquals(6, parsed.shadowMaxFacesPerFrame());
        assertEquals(0.8f, parsed.shadowRtDenoiseStrength());
        assertEquals(120.0f, parsed.shadowRtRayLength());
        assertEquals(4, parsed.shadowRtSampleCount());
        assertEquals(0.9f, parsed.shadowRtDedicatedDenoiseStrength());
        assertEquals(160.0f, parsed.shadowRtDedicatedRayLength());
        assertEquals(8, parsed.shadowRtDedicatedSampleCount());
        assertEquals(0.93f, parsed.shadowRtProductionDenoiseStrength());
        assertEquals(220.0f, parsed.shadowRtProductionRayLength());
        assertEquals(12, parsed.shadowRtProductionSampleCount());
        assertEquals(1.4f, parsed.shadowPcssSoftness());
        assertEquals(0.9f, parsed.shadowMomentBlend());
        assertEquals(1.2f, parsed.shadowMomentBleedReduction());
        assertEquals(1.5f, parsed.shadowContactStrength());
        assertEquals(1.8f, parsed.shadowContactTemporalMotionScale());
        assertEquals(0.55f, parsed.shadowContactTemporalMinStability());
        assertEquals(false, parsed.shadowSchedulerEnabled());
        assertEquals(2, parsed.shadowSchedulerHeroPeriod());
        assertEquals(3, parsed.shadowSchedulerMidPeriod());
        assertEquals(8, parsed.shadowSchedulerDistantPeriod());
        assertEquals(false, parsed.shadowDirectionalTexelSnapEnabled());
        assertEquals(1.75f, parsed.shadowDirectionalTexelSnapScale());
        assertEquals(2, parsed.reflectionProbeChurnWarnMinDelta());
        assertEquals(5, parsed.reflectionProbeChurnWarnMinStreak());
        assertEquals(240, parsed.reflectionProbeChurnWarnCooldownFrames());
        assertEquals(12, parsed.reflectionProbeQualityOverlapWarnMaxPairs());
        assertEquals(2, parsed.reflectionProbeQualityBleedRiskWarnMaxPairs());
        assertEquals(3, parsed.reflectionProbeQualityMinOverlapPairsWhenMultiple());
        assertEquals(0.82, parsed.reflectionProbeQualityBoxProjectionMinRatio());
        assertEquals(4, parsed.reflectionProbeQualityInvalidBlendDistanceWarnMax());
        assertEquals(0.27, parsed.reflectionProbeQualityOverlapCoverageWarnMin());
        assertEquals(0.42, parsed.reflectionSsrTaaInstabilityRejectMin());
        assertEquals(0.61, parsed.reflectionSsrTaaInstabilityConfidenceMax());
        assertEquals(3L, parsed.reflectionSsrTaaInstabilityDropEventsMin());
        assertEquals(6, parsed.reflectionSsrTaaInstabilityWarnMinFrames());
        assertEquals(180, parsed.reflectionSsrTaaInstabilityWarnCooldownFrames());
        assertEquals(0.35, parsed.reflectionSsrTaaRiskEmaAlpha());
        assertEquals(true, parsed.reflectionSsrTaaAdaptiveEnabled());
        assertEquals(0.21, parsed.reflectionSsrTaaAdaptiveTemporalBoostMax());
        assertEquals(0.63, parsed.reflectionSsrTaaAdaptiveSsrStrengthScaleMin());
        assertEquals(0.28, parsed.reflectionSsrTaaAdaptiveStepScaleBoostMax());
        assertEquals(240, parsed.reflectionSsrTaaAdaptiveTrendWindowFrames());
        assertEquals(0.52, parsed.reflectionSsrTaaAdaptiveTrendHighRatioWarnMin());
        assertEquals(5, parsed.reflectionSsrTaaAdaptiveTrendWarnMinFrames());
        assertEquals(210, parsed.reflectionSsrTaaAdaptiveTrendWarnCooldownFrames());
        assertEquals(44, parsed.reflectionSsrTaaAdaptiveTrendWarnMinSamples());
        assertEquals(0.36, parsed.reflectionSsrTaaAdaptiveTrendSloMeanSeverityMax());
        assertEquals(0.19, parsed.reflectionSsrTaaAdaptiveTrendSloHighRatioMax());
        assertEquals(28, parsed.reflectionSsrTaaAdaptiveTrendSloMinSamples());
        assertEquals(0.81, parsed.reflectionSsrTaaHistoryRejectSeverityMin());
        assertEquals(0.51, parsed.reflectionSsrTaaHistoryConfidenceDecaySeverityMin());
        assertEquals(7, parsed.reflectionSsrTaaHistoryRejectRiskStreakMin());
        assertEquals(6L, parsed.reflectionSsrTaaDisocclusionRejectDropEventsMin());
        assertEquals(0.57, parsed.reflectionSsrTaaDisocclusionRejectConfidenceMax());
        assertEquals(0.39, parsed.reflectionSsrEnvelopeRejectWarnMax());
        assertEquals(0.62, parsed.reflectionSsrEnvelopeConfidenceWarnMin());
        assertEquals(5L, parsed.reflectionSsrEnvelopeDropWarnMin());
        assertEquals(4, parsed.reflectionSsrEnvelopeWarnMinFrames());
        assertEquals(180, parsed.reflectionSsrEnvelopeWarnCooldownFrames());
        assertEquals(true, parsed.reflectionRtSingleBounceEnabled());
        assertEquals(true, parsed.reflectionRtMultiBounceEnabled());
        assertEquals(true, parsed.reflectionRtRequireActive());
        assertEquals(true, parsed.reflectionRtRequireMultiBounce());
        assertEquals(true, parsed.reflectionRtRequireDedicatedPipeline());
        assertEquals(true, parsed.reflectionRtDedicatedPipelineEnabled());
        assertEquals(false, parsed.reflectionRtDedicatedDenoisePipelineEnabled());
        assertEquals(0.73, parsed.reflectionRtDenoiseStrength());
        assertEquals(1.3, parsed.reflectionRtPerfMaxGpuMsLow());
        assertEquals(2.1, parsed.reflectionRtPerfMaxGpuMsMedium());
        assertEquals(2.9, parsed.reflectionRtPerfMaxGpuMsHigh());
        assertEquals(3.7, parsed.reflectionRtPerfMaxGpuMsUltra());
        assertEquals(5, parsed.reflectionRtPerfWarnMinFrames());
        assertEquals(210, parsed.reflectionRtPerfWarnCooldownFrames());
        assertEquals(0.62, parsed.reflectionRtHybridProbeShareWarnMax());
        assertEquals(6, parsed.reflectionRtHybridWarnMinFrames());
        assertEquals(190, parsed.reflectionRtHybridWarnCooldownFrames());
        assertEquals(0.33, parsed.reflectionRtDenoiseSpatialVarianceWarnMax());
        assertEquals(0.27, parsed.reflectionRtDenoiseTemporalLagWarnMax());
        assertEquals(4, parsed.reflectionRtDenoiseWarnMinFrames());
        assertEquals(160, parsed.reflectionRtDenoiseWarnCooldownFrames());
        assertEquals(1.9, parsed.reflectionRtAsBuildGpuMsWarnMax());
        assertEquals(88.0, parsed.reflectionRtAsMemoryBudgetMb());
        assertEquals(0.41, parsed.reflectionTransparencyCandidateReactiveMin());
        assertEquals(0.57, parsed.reflectionTransparencyProbeOnlyRatioWarnMax());
        assertEquals(5, parsed.reflectionTransparencyWarnMinFrames());
        assertEquals(220, parsed.reflectionTransparencyWarnCooldownFrames());
        assertEquals(true, parsed.reflectionPlanarPerfRequireGpuTimestamp());
        assertEquals(6, parsed.reflectionProbeUpdateCadenceFrames());
        assertEquals(48, parsed.reflectionProbeMaxVisible());
        assertEquals(1.8, parsed.reflectionProbeLodDepthScale());
        assertEquals(7, parsed.reflectionProbeStreamingWarnMinFrames());
        assertEquals(222, parsed.reflectionProbeStreamingWarnCooldownFrames());
        assertEquals(0.24, parsed.reflectionProbeStreamingMissRatioWarnMax());
        assertEquals(0.41, parsed.reflectionProbeStreamingDeferredRatioWarnMax());
        assertEquals(0.66, parsed.reflectionProbeStreamingLodSkewWarnMax());
        assertEquals(96.0, parsed.reflectionProbeStreamingMemoryBudgetMb());
    }

    @Test
    void parseShadowSchedulerOverridesFallbackToBounds() {
        VulkanRuntimeOptions.Parsed parsed = VulkanRuntimeOptions.parse(
                Map.ofEntries(
                        Map.entry("vulkan.shadow.maxLocalShadowLayers", "99"),
                        Map.entry("vulkan.shadow.maxShadowFacesPerFrame", "-1"),
                        Map.entry("vulkan.shadow.maxShadowedLocalLights", "99"),
                        Map.entry("vulkan.shadow.rtDenoiseStrength", "7.0"),
                        Map.entry("vulkan.shadow.rtRayLength", "0.1"),
                        Map.entry("vulkan.shadow.rtSampleCount", "99"),
                        Map.entry("vulkan.shadow.rtDedicatedDenoiseStrength", "7.0"),
                        Map.entry("vulkan.shadow.rtDedicatedRayLength", "0.1"),
                        Map.entry("vulkan.shadow.rtDedicatedSampleCount", "99"),
                        Map.entry("vulkan.shadow.rtProductionDenoiseStrength", "7.0"),
                        Map.entry("vulkan.shadow.rtProductionRayLength", "0.1"),
                        Map.entry("vulkan.shadow.rtProductionSampleCount", "99"),
                        Map.entry("vulkan.shadow.pcssSoftness", "9.0"),
                        Map.entry("vulkan.shadow.momentBlend", "0.1"),
                        Map.entry("vulkan.shadow.momentBleedReduction", "7.0"),
                        Map.entry("vulkan.shadow.contactStrength", "-1.0"),
                        Map.entry("vulkan.shadow.contactTemporalMotionScale", "-1.0"),
                        Map.entry("vulkan.shadow.contactTemporalMinStability", "1.5"),
                        Map.entry("vulkan.shadow.directionalTexelSnapScale", "10.0"),
                        Map.entry("vulkan.reflections.probeChurnWarnMinDelta", "0"),
                        Map.entry("vulkan.reflections.probeChurnWarnMinStreak", "0"),
                        Map.entry("vulkan.reflections.probeChurnWarnCooldownFrames", "999999"),
                        Map.entry("vulkan.reflections.probeQualityOverlapWarnMaxPairs", "-1"),
                        Map.entry("vulkan.reflections.probeQualityBleedRiskWarnMaxPairs", "-1"),
                        Map.entry("vulkan.reflections.probeQualityMinOverlapPairsWhenMultiple", "-1"),
                        Map.entry("vulkan.reflections.probeQualityBoxProjectionMinRatio", "5.0"),
                        Map.entry("vulkan.reflections.probeQualityInvalidBlendDistanceWarnMax", "-4"),
                        Map.entry("vulkan.reflections.probeQualityOverlapCoverageWarnMin", "-2.0"),
                        Map.entry("vulkan.reflections.ssrTaaInstabilityRejectMin", "9.0"),
                        Map.entry("vulkan.reflections.ssrTaaInstabilityConfidenceMax", "-2.0"),
                        Map.entry("vulkan.reflections.ssrTaaInstabilityDropEventsMin", "-5"),
                        Map.entry("vulkan.reflections.ssrTaaInstabilityWarnMinFrames", "0"),
                        Map.entry("vulkan.reflections.ssrTaaInstabilityWarnCooldownFrames", "999999"),
                        Map.entry("vulkan.reflections.ssrTaaRiskEmaAlpha", "7.0"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTemporalBoostMax", "9.0"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveSsrStrengthScaleMin", "-1.0"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveStepScaleBoostMax", "2.0"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendWindowFrames", "2"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendHighRatioWarnMin", "2.0"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendWarnMinFrames", "0"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendWarnCooldownFrames", "999999"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendWarnMinSamples", "0"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendSloMeanSeverityMax", "2.0"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendSloHighRatioMax", "-1.0"),
                        Map.entry("vulkan.reflections.ssrTaaAdaptiveTrendSloMinSamples", "0"),
                        Map.entry("vulkan.reflections.ssrTaaHistoryRejectSeverityMin", "2.0"),
                        Map.entry("vulkan.reflections.ssrTaaHistoryConfidenceDecaySeverityMin", "-1.0"),
                        Map.entry("vulkan.reflections.ssrTaaHistoryRejectRiskStreakMin", "0"),
                        Map.entry("vulkan.reflections.ssrTaaDisocclusionRejectDropEventsMin", "-9"),
                        Map.entry("vulkan.reflections.ssrTaaDisocclusionRejectConfidenceMax", "9.0"),
                        Map.entry("vulkan.reflections.ssrEnvelopeRejectWarnMax", "2.0"),
                        Map.entry("vulkan.reflections.ssrEnvelopeConfidenceWarnMin", "-2.0"),
                        Map.entry("vulkan.reflections.ssrEnvelopeDropWarnMin", "-1"),
                        Map.entry("vulkan.reflections.ssrEnvelopeWarnMinFrames", "0"),
                        Map.entry("vulkan.reflections.ssrEnvelopeWarnCooldownFrames", "999999"),
                        Map.entry("vulkan.reflections.rtDedicatedDenoisePipelineEnabled", "true"),
                        Map.entry("vulkan.reflections.rtRequireActive", "true"),
                        Map.entry("vulkan.reflections.rtRequireMultiBounce", "true"),
                        Map.entry("vulkan.reflections.rtRequireDedicatedPipeline", "true"),
                        Map.entry("vulkan.reflections.rtDedicatedPipelineEnabled", "true"),
                        Map.entry("vulkan.reflections.rtDenoiseStrength", "9.0"),
                        Map.entry("vulkan.reflections.rtPerfMaxGpuMsLow", "-1.0"),
                        Map.entry("vulkan.reflections.rtPerfMaxGpuMsMedium", "20000.0"),
                        Map.entry("vulkan.reflections.rtPerfMaxGpuMsHigh", "-1.0"),
                        Map.entry("vulkan.reflections.rtPerfMaxGpuMsUltra", "20000.0"),
                        Map.entry("vulkan.reflections.rtPerfWarnMinFrames", "0"),
                        Map.entry("vulkan.reflections.rtPerfWarnCooldownFrames", "999999"),
                        Map.entry("vulkan.reflections.rtHybridProbeShareWarnMax", "2.0"),
                        Map.entry("vulkan.reflections.rtHybridWarnMinFrames", "0"),
                        Map.entry("vulkan.reflections.rtHybridWarnCooldownFrames", "999999"),
                        Map.entry("vulkan.reflections.rtDenoiseSpatialVarianceWarnMax", "-1.0"),
                        Map.entry("vulkan.reflections.rtDenoiseTemporalLagWarnMax", "2.0"),
                        Map.entry("vulkan.reflections.rtDenoiseWarnMinFrames", "0"),
                        Map.entry("vulkan.reflections.rtDenoiseWarnCooldownFrames", "999999"),
                        Map.entry("vulkan.reflections.rtAsBuildGpuMsWarnMax", "-1.0"),
                        Map.entry("vulkan.reflections.rtAsMemoryBudgetMb", "99999.0"),
                        Map.entry("vulkan.reflections.transparencyCandidateReactiveMin", "9.0"),
                        Map.entry("vulkan.reflections.transparencyProbeOnlyRatioWarnMax", "-9.0"),
                        Map.entry("vulkan.reflections.transparencyWarnMinFrames", "0"),
                        Map.entry("vulkan.reflections.transparencyWarnCooldownFrames", "999999"),
                        Map.entry("vulkan.reflections.probeUpdateCadenceFrames", "0"),
                        Map.entry("vulkan.reflections.probeMaxVisible", "999"),
                        Map.entry("vulkan.reflections.probeLodDepthScale", "9.0"),
                        Map.entry("vulkan.reflections.probeStreamingWarnMinFrames", "0"),
                        Map.entry("vulkan.reflections.probeStreamingWarnCooldownFrames", "999999"),
                        Map.entry("vulkan.reflections.probeStreamingMissRatioWarnMax", "-2.0"),
                        Map.entry("vulkan.reflections.probeStreamingDeferredRatioWarnMax", "9.0"),
                        Map.entry("vulkan.reflections.probeStreamingLodSkewWarnMax", "2.0"),
                        Map.entry("vulkan.reflections.probeStreamingMemoryBudgetMb", "99999.0")
                ),
                256
        );

        assertEquals(8, parsed.shadowMaxShadowedLocalLights());
        assertEquals(24, parsed.shadowMaxLocalLayers());
        assertEquals(0, parsed.shadowMaxFacesPerFrame());
        assertEquals(1.0f, parsed.shadowRtDenoiseStrength());
        assertEquals(1.0f, parsed.shadowRtRayLength());
        assertEquals(16, parsed.shadowRtSampleCount());
        assertEquals(1.0f, parsed.shadowRtDedicatedDenoiseStrength());
        assertEquals(0.1f, parsed.shadowRtDedicatedRayLength());
        assertEquals(16, parsed.shadowRtDedicatedSampleCount());
        assertEquals(1.0f, parsed.shadowRtProductionDenoiseStrength());
        assertEquals(0.1f, parsed.shadowRtProductionRayLength());
        assertEquals(16, parsed.shadowRtProductionSampleCount());
        assertEquals(2.0f, parsed.shadowPcssSoftness());
        assertEquals(0.25f, parsed.shadowMomentBlend());
        assertEquals(1.5f, parsed.shadowMomentBleedReduction());
        assertEquals(0.25f, parsed.shadowContactStrength());
        assertEquals(0.1f, parsed.shadowContactTemporalMotionScale());
        assertEquals(1.0f, parsed.shadowContactTemporalMinStability());
        assertEquals(false, parsed.shadowRtBvhStrict());
        assertEquals(true, parsed.shadowSchedulerEnabled());
        assertEquals(1, parsed.shadowSchedulerHeroPeriod());
        assertEquals(2, parsed.shadowSchedulerMidPeriod());
        assertEquals(4, parsed.shadowSchedulerDistantPeriod());
        assertEquals(true, parsed.shadowDirectionalTexelSnapEnabled());
        assertEquals(4.0f, parsed.shadowDirectionalTexelSnapScale());
        assertEquals(1, parsed.reflectionProbeChurnWarnMinDelta());
        assertEquals(1, parsed.reflectionProbeChurnWarnMinStreak());
        assertEquals(10000, parsed.reflectionProbeChurnWarnCooldownFrames());
        assertEquals(0, parsed.reflectionProbeQualityOverlapWarnMaxPairs());
        assertEquals(0, parsed.reflectionProbeQualityBleedRiskWarnMaxPairs());
        assertEquals(0, parsed.reflectionProbeQualityMinOverlapPairsWhenMultiple());
        assertEquals(1.0, parsed.reflectionProbeQualityBoxProjectionMinRatio());
        assertEquals(0, parsed.reflectionProbeQualityInvalidBlendDistanceWarnMax());
        assertEquals(0.0, parsed.reflectionProbeQualityOverlapCoverageWarnMin());
        assertEquals(1.0, parsed.reflectionSsrTaaInstabilityRejectMin());
        assertEquals(0.0, parsed.reflectionSsrTaaInstabilityConfidenceMax());
        assertEquals(0L, parsed.reflectionSsrTaaInstabilityDropEventsMin());
        assertEquals(1, parsed.reflectionSsrTaaInstabilityWarnMinFrames());
        assertEquals(10000, parsed.reflectionSsrTaaInstabilityWarnCooldownFrames());
        assertEquals(1.0, parsed.reflectionSsrTaaRiskEmaAlpha());
        assertEquals(false, parsed.reflectionSsrTaaAdaptiveEnabled());
        assertEquals(0.4, parsed.reflectionSsrTaaAdaptiveTemporalBoostMax());
        assertEquals(0.2, parsed.reflectionSsrTaaAdaptiveSsrStrengthScaleMin());
        assertEquals(1.0, parsed.reflectionSsrTaaAdaptiveStepScaleBoostMax());
        assertEquals(8, parsed.reflectionSsrTaaAdaptiveTrendWindowFrames());
        assertEquals(1.0, parsed.reflectionSsrTaaAdaptiveTrendHighRatioWarnMin());
        assertEquals(1, parsed.reflectionSsrTaaAdaptiveTrendWarnMinFrames());
        assertEquals(10000, parsed.reflectionSsrTaaAdaptiveTrendWarnCooldownFrames());
        assertEquals(1, parsed.reflectionSsrTaaAdaptiveTrendWarnMinSamples());
        assertEquals(1.0, parsed.reflectionSsrTaaAdaptiveTrendSloMeanSeverityMax());
        assertEquals(0.0, parsed.reflectionSsrTaaAdaptiveTrendSloHighRatioMax());
        assertEquals(1, parsed.reflectionSsrTaaAdaptiveTrendSloMinSamples());
        assertEquals(1.0, parsed.reflectionSsrTaaHistoryRejectSeverityMin());
        assertEquals(0.0, parsed.reflectionSsrTaaHistoryConfidenceDecaySeverityMin());
        assertEquals(1, parsed.reflectionSsrTaaHistoryRejectRiskStreakMin());
        assertEquals(0L, parsed.reflectionSsrTaaDisocclusionRejectDropEventsMin());
        assertEquals(1.0, parsed.reflectionSsrTaaDisocclusionRejectConfidenceMax());
        assertEquals(1.0, parsed.reflectionSsrEnvelopeRejectWarnMax());
        assertEquals(0.0, parsed.reflectionSsrEnvelopeConfidenceWarnMin());
        assertEquals(0L, parsed.reflectionSsrEnvelopeDropWarnMin());
        assertEquals(1, parsed.reflectionSsrEnvelopeWarnMinFrames());
        assertEquals(10000, parsed.reflectionSsrEnvelopeWarnCooldownFrames());
        assertEquals(true, parsed.reflectionRtSingleBounceEnabled());
        assertEquals(false, parsed.reflectionRtMultiBounceEnabled());
        assertEquals(true, parsed.reflectionRtRequireActive());
        assertEquals(true, parsed.reflectionRtRequireMultiBounce());
        assertEquals(true, parsed.reflectionRtRequireDedicatedPipeline());
        assertEquals(true, parsed.reflectionRtDedicatedPipelineEnabled());
        assertEquals(true, parsed.reflectionRtDedicatedDenoisePipelineEnabled());
        assertEquals(1.0, parsed.reflectionRtDenoiseStrength());
        assertEquals(0.0, parsed.reflectionRtPerfMaxGpuMsLow());
        assertEquals(1000.0, parsed.reflectionRtPerfMaxGpuMsMedium());
        assertEquals(0.0, parsed.reflectionRtPerfMaxGpuMsHigh());
        assertEquals(1000.0, parsed.reflectionRtPerfMaxGpuMsUltra());
        assertEquals(1, parsed.reflectionRtPerfWarnMinFrames());
        assertEquals(10000, parsed.reflectionRtPerfWarnCooldownFrames());
        assertEquals(1.0, parsed.reflectionRtHybridProbeShareWarnMax());
        assertEquals(1, parsed.reflectionRtHybridWarnMinFrames());
        assertEquals(10000, parsed.reflectionRtHybridWarnCooldownFrames());
        assertEquals(0.0, parsed.reflectionRtDenoiseSpatialVarianceWarnMax());
        assertEquals(1.0, parsed.reflectionRtDenoiseTemporalLagWarnMax());
        assertEquals(1, parsed.reflectionRtDenoiseWarnMinFrames());
        assertEquals(10000, parsed.reflectionRtDenoiseWarnCooldownFrames());
        assertEquals(0.0, parsed.reflectionRtAsBuildGpuMsWarnMax());
        assertEquals(4096.0, parsed.reflectionRtAsMemoryBudgetMb());
        assertEquals(1.0, parsed.reflectionTransparencyCandidateReactiveMin());
        assertEquals(0.0, parsed.reflectionTransparencyProbeOnlyRatioWarnMax());
        assertEquals(1, parsed.reflectionTransparencyWarnMinFrames());
        assertEquals(10000, parsed.reflectionTransparencyWarnCooldownFrames());
        assertEquals(false, parsed.reflectionPlanarPerfRequireGpuTimestamp());
        assertEquals(1, parsed.reflectionProbeUpdateCadenceFrames());
        assertEquals(256, parsed.reflectionProbeMaxVisible());
        assertEquals(4.0, parsed.reflectionProbeLodDepthScale());
        assertEquals(1, parsed.reflectionProbeStreamingWarnMinFrames());
        assertEquals(10000, parsed.reflectionProbeStreamingWarnCooldownFrames());
        assertEquals(0.0, parsed.reflectionProbeStreamingMissRatioWarnMax());
        assertEquals(1.0, parsed.reflectionProbeStreamingDeferredRatioWarnMax());
        assertEquals(1.0, parsed.reflectionProbeStreamingLodSkewWarnMax());
        assertEquals(4096.0, parsed.reflectionProbeStreamingMemoryBudgetMb());
    }
}
